//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Broadband {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YourPrice_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YourPrice_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Broadband.YourPrice_Resources", typeof(YourPrice_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection charge.
        /// </summary>
        public static string ConnectionCharge {
            get {
                return ResourceManager.GetString("ConnectionCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your basket.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to included.
        /// </summary>
        public static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone line installation fee.
        /// </summary>
        public static string InstallationFee {
            get {
                return ResourceManager.GetString("InstallationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line rental only.
        /// </summary>
        public static string LineRental {
            get {
                return ResourceManager.GetString("LineRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies after 12 months.
        /// </summary>
        public static string NonEnergySurchargeDescription {
            get {
                return ResourceManager.GetString("NonEnergySurchargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-off costs:.
        /// </summary>
        public static string OneOffHeader {
            get {
                return ResourceManager.GetString("OneOffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn’t look like you have an active Openreach/BT phone line, so we&apos;ll contact you to arrange a date for an engineer to install one. We&apos;ll let you know if they need access to your home as you&apos;ll need to be there. There&apos;s a one-off charge of £60 which we&apos;ll add to a future bill..
        /// </summary>
        public static string OneOffModalContent1 {
            get {
                return ResourceManager.GetString("OneOffModalContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There’s no connection charge to connect to our services..
        /// </summary>
        public static string OneOffModalContent2 {
            get {
                return ResourceManager.GetString("OneOffModalContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One off costs.
        /// </summary>
        public static string OneOffModalHeader {
            get {
                return ResourceManager.GetString("OneOffModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your £60 phone line installation fee.
        /// </summary>
        public static string OneOffModalSubHeader1 {
            get {
                return ResourceManager.GetString("OneOffModalSubHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection charge.
        /// </summary>
        public static string OneOffModalSubHeader2 {
            get {
                return ResourceManager.GetString("OneOffModalSubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited Fibre.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly cost:.
        /// </summary>
        public static string SectionTotalHeader {
            get {
                return ResourceManager.GetString("SectionTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly costs.
        /// </summary>
        public static string SubHeader {
            get {
                return ResourceManager.GetString("SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-off costs.
        /// </summary>
        public static string SubHeader2 {
            get {
                return ResourceManager.GetString("SubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monthly bill*.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Excluding phone calls &amp; optional call features.
        /// </summary>
        public static string TotalDisclaimer {
            get {
                return ResourceManager.GetString("TotalDisclaimer", resourceCulture);
            }
        }
    }
}
