//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Accordion_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Accordion_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.Accordion_Resources", typeof(Accordion_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices for energy products include 5% VAT. Your Bundle energy product has an {0}-month fixed-term contract that begins on the day your supply switches to us..
        /// </summary>
        public static string AboutYourBundleEnergyPara1 {
            get {
                return ResourceManager.GetString("AboutYourBundleEnergyPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} months, we’ll move you onto our Standard variable tariff for energy, but we’ll contact you before that to let you know our latest tariffs..
        /// </summary>
        public static string AboutYourBundleEnergyPara2 {
            get {
                return ResourceManager.GetString("AboutYourBundleEnergyPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send your Welcome pack by email. This includes your confirmation of contract, tariff information, terms and conditions and cancellation form..
        /// </summary>
        public static string AboutYourBundleEnergyPara3 {
            get {
                return ResourceManager.GetString("AboutYourBundleEnergyPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices for broadband and phone products include 20% VAT..
        /// </summary>
        public static string AboutYourBundlePara1 {
            get {
                return ResourceManager.GetString("AboutYourBundlePara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bundle broadband and phone product has an 18-month fixed-term contract which begins on the day your service starts. You may have to pay early termination charges if you cancel your service before the end of that term (see terms and conditions below)..
        /// </summary>
        public static string AboutYourBundlePara2 {
            get {
                return ResourceManager.GetString("AboutYourBundlePara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 18 months, your Phone and Broadband contract will roll onto a non-fixed-term contract. The current cost of this is {0} per month, but prices are subject to change. We’ll remind you before the end of your contract that your package price will change..
        /// </summary>
        public static string AboutYourBundlePara3 {
            get {
                return ResourceManager.GetString("AboutYourBundlePara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send you a Welcome pack by email with full details about your product..
        /// </summary>
        public static string AboutYourBundlePara4 {
            get {
                return ResourceManager.GetString("AboutYourBundlePara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Breakdown includes 20% VAT and Insurance Premium Tax..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara1 {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Cover includes 20% VAT and Insurance Premium Tax..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara1_FixNProtectPlus {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara1_FixNProtectPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown has a 12-month fixed-term contract which begins on the next working day after your energy supply switches to us..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara2 {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover has a 12-month fixed-term contract which begins on the next working day after your energy supply switches to us..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara2_FixNProtectPlus {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara2_FixNProtectPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll write to you at least 14 days before your 12-month contract ends. We’ll let you know your new price before we renew your cover for a further 12 months. You’ll then be able to change your level of cover or cancel your renewal, as you wish..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara3 {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send you a Welcome pack by post with full details about your product, including your Confirmation of Sale letter..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara4 {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll be contacted to arrange an initial system inspection..
        /// </summary>
        public static string AboutYourHomeServicesBundlePara4_FixNProtectPlus {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara4_FixNProtectPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you confirm your order, please read the full terms and conditions:.
        /// </summary>
        public static string AboutYourHomeServicesBundlePara5 {
            get {
                return ResourceManager.GetString("AboutYourHomeServicesBundlePara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your switch.
        /// </summary>
        public static string AboutYourSwitchHeader {
            get {
                return ResourceManager.GetString("AboutYourSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll contact your current provider to let them know you’re switching to us, unless you’re with Virgin Media. Virgin Media customers need contact the company directly to cancel their service..
        /// </summary>
        public static string AboutYourSwitchPara1 {
            get {
                return ResourceManager.GetString("AboutYourSwitchPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching takes around 18 to 20 days for most customers..
        /// </summary>
        public static string AboutYourSwitchPara2 {
            get {
                return ResourceManager.GetString("AboutYourSwitchPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles - important information.
        /// </summary>
        public static string AccordionBundleSubHeader {
            get {
                return ResourceManager.GetString("AccordionBundleSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles – important information.
        /// </summary>
        public static string AccordionBundleSubHeaderAlt {
            get {
                return ResourceManager.GetString("AccordionBundleSubHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy tariffs - important information.
        /// </summary>
        public static string AccordionEnergySubHeader {
            get {
                return ResourceManager.GetString("AccordionEnergySubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy tariffs – important information.
        /// </summary>
        public static string AccordionEnergySubHeaderAlt {
            get {
                return ResourceManager.GetString("AccordionEnergySubHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you need to know.
        /// </summary>
        public static string AccordionHeader {
            get {
                return ResourceManager.GetString("AccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How your savings are calculated.
        /// </summary>
        public static string AccordionSavingsCalculationHeader {
            get {
                return ResourceManager.GetString("AccordionSavingsCalculationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How your savings are calculated.
        /// </summary>
        public static string AccordionSavingsCalculationHeaderAlt {
            get {
                return ResourceManager.GetString("AccordionSavingsCalculationHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £114 saving is based on Heating Breakdown being free for 12 months compared to the standard price.
        /// </summary>
        public static string AccordionSavingsCalculationPara1 {
            get {
                return ResourceManager.GetString("AccordionSavingsCalculationPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy is for owners of domestic properties only. Retail, commercial and other premises used for business are not eligible..
        /// </summary>
        public static string AreYouEligibleForHomeServicesPara1 {
            get {
                return ResourceManager.GetString("AreYouEligibleForHomeServicesPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are protecting the boiler at your property it must have a power output of less than 70 kW/hr and be powered by natural gas. Boilers powered by liquified petroleum gas (LPG), oil, renewable heat sources and electric are not covered..
        /// </summary>
        public static string AreYouEligibleForHomeServicesPara2 {
            get {
                return ResourceManager.GetString("AreYouEligibleForHomeServicesPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not cover any models for the following brands of boiler: Servowarm, Chaffoteaux or Ferroli. Additionally, we do not cover the Ideal Istor boiler or any thermal store products made by Gledhill..
        /// </summary>
        public static string AreYouEligibleForHomeServicesPara3 {
            get {
                return ResourceManager.GetString("AreYouEligibleForHomeServicesPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boilers with long-term and obvious pre-existing faults or system deficiencies, as determined by our engineer acting reasonably, are not covered..
        /// </summary>
        public static string AreYouEligibleForHomeServicesPara4 {
            get {
                return ResourceManager.GetString("AreYouEligibleForHomeServicesPara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you confirm your order, please read the full terms and conditions:.
        /// </summary>
        public static string BeforeYouConfirmPara {
            get {
                return ResourceManager.GetString("BeforeYouConfirmPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £180 saving is based on £10.00 (43%) discount for 18 months for fibre broadband (18 x £10.00 = £180), when compared to buying Unlimited Fibre, our equivalent standalone broadband product (£23)..
        /// </summary>
        public static string BroadbandBundleSavingsPara1 {
            get {
                return ResourceManager.GetString("BroadbandBundleSavingsPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How your savings are calculated.
        /// </summary>
        public static string BroadbandBundleSavingsSubHeader {
            get {
                return ResourceManager.GetString("BroadbandBundleSavingsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How your savings are calculated.
        /// </summary>
        public static string BroadbandBundleSavingsSubHeaderAlt {
            get {
                return ResourceManager.GetString("BroadbandBundleSavingsSubHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband &amp; Phone details.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsHeader {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices for broadband and phone products include 20% VAT. Your Bundle broadband and phone product has an 18-month fixed-term contract which begins on the day your service starts. The price displayed is the monthly cost of the broadband, phone line and optional call package for the duration of your contract (excluding additional calls and features)..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara1 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 18 months, your phone and broadband contract will roll onto a non-fixed-term contract. The current cost of this is £28 per month, but prices are subject to change. We’ll remind you before the end of your contract that your package price will change..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara2 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An early exit fee of 38 pence per remaining day of your contract applies if you cancel your service before the end of that term. For details about cancellation and early termination charges, see our full terms and conditions below..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara3 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our broadband and phone packages are available to customers with an active BT Openreach phone line. If you don’t have one, we can install one for you. There&apos;s a one-off charge of £60 which we&apos;ll add to a future bill..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara4 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upgrade your broadband package at any time but this may terminate the discount earlier than 18 months. You can change your phone package at any time without affecting the discount you are receiving..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara5 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our price promise is to keep phone and broadband package prices fixed for the duration of your contract from your package start date. The only exception will be any increases to VAT or any other relevant tax or levy. The monthly package price includes your monthly broadband, line rental and selected call package..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara6 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’re not happy with any aspect of the service you have received, and we have been unable to fix the problem, you can leave your contract without early termination charges within the first 60 days. For more details, see the .
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara7_1 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE 60-Day Broadband Happiness Guarantee.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara7_Link1Alt {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara7_Link1Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE 60-Day Broadband Happiness Guarantee.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara7_Link1Text {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara7_Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband speed and unlimited downloads are subject to our.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_1 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Broadband Traffic Management Policy.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_1Link1Alt {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_1Link1Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband Traffic Management.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_1Link1Text {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_1Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Acceptable Use Policy.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_1Link2Alt {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_1Link2Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable Use.
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_1Link2Text {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_1Link2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_2 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  policies..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_3 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual speeds are dependent upon length and quality of the copper line between your home and your exchange or street cabinet as well as environmental factors within you home such as Wi-Fi interference, in-home wiring and congestion on the service you are accessing..
        /// </summary>
        public static string BundleBroadbandPhoneDetailsPara8_4 {
            get {
                return ResourceManager.GetString("BundleBroadbandPhoneDetailsPara8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy details.
        /// </summary>
        public static string BundleEnergyDetailsHeader {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices for energy products include 5% VAT. Bundle energy products have either a 12-month or an 18-month fixed-term contract that begins on the day your supply switches to us..
        /// </summary>
        public static string BundleEnergyDetailsPara1 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After your fixed-term contract ends, we’ll move you onto our Standard variable tariff for energy, but we’ll contact you before that to let you know our latest tariffs..
        /// </summary>
        public static string BundleEnergyDetailsPara2 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up to this fixed price energy product, you are registering your interest for a smart meter. This means we may contact you in the future to discuss a smart meter installation as and when you become eligible. We rely on a mobile phone or wireless signal to get your smart meter readings. If these fail, you’ll either need to take your own reading and send it to us, or your bills will be estimated..
        /// </summary>
        public static string BundleEnergyDetailsPara3 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we’re taking over the supply of energy from another supplier, you agree to your current supplier transferring the right for us to collect any debt you owe them (in the event we’re obliged to)..
        /// </summary>
        public static string BundleEnergyDetailsPara4 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By choosing a fixed-term tariff and paying by Direct Debit, you’ll get a discount of £40 a year for each fuel compared to another way of paying. This discount is applied to your standing charge on a pence per day basis until your tariff ends. Discounts do not apply to customers on an Energy Assist tariff or with a Pay As You Go meter..
        /// </summary>
        public static string BundleEnergyDetailsPara5 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Green Deal Scheme in place for your home, Green Deal Charges will also apply. The estimates included in this application do not include Green Deal Charges. We will write to you separately to confirm if a Green Deal Charge applies..
        /// </summary>
        public static string BundleEnergyDetailsPara6 {
            get {
                return ResourceManager.GetString("BundleEnergyDetailsPara6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more details, please read our full terms and conditions below..
        /// </summary>
        public static string BundleFullTermsAndConditionsPara {
            get {
                return ResourceManager.GetString("BundleFullTermsAndConditionsPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Breakdown Cover Policy Booklet.
        /// </summary>
        public static string BundleHeatingBreakdownCoverPolicyLinkAlt {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownCoverPolicyLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Breakdown Cover Policy Booklet.
        /// </summary>
        public static string BundleHeatingBreakdownCoverPolicyLinkText {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownCoverPolicyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown details.
        /// </summary>
        public static string BundleHeatingBreakdownDetailsHeader {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Breakdown includes 20% VAT and Insurance Premium Tax. Heating Breakdown has a 12-month fixed-term contract which begins on the next working day after your energy supply switches to us..
        /// </summary>
        public static string BundleHeatingBreakdownDetailsPara1 {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll write to you at least 14 days before your 12-month contract ends. We’ll let you know your new price before we renew your cover for a further 12 months. You’ll then be able to change your level of cover or cancel your renewal, as you wish..
        /// </summary>
        public static string BundleHeatingBreakdownDetailsPara2 {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cover has a £90 excess, which means you&apos;d pay £90 each time you need to make a claim..
        /// </summary>
        public static string BundleHeatingBreakdownDetailsPara3 {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and labour are subject to terms and conditions found in the.
        /// </summary>
        public static string BundleHeatingBreakdownDetailsPara4_1 {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsPara4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy is for owners of domestic properties only. Retail, commercial and other premises used for business are not eligible..
        /// </summary>
        public static string BundleHeatingBreakdownDetailsPara5 {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownDetailsPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Heating Breakdown Cover Insurance Product Information Document.
        /// </summary>
        public static string BundleHeatingBreakdownInsurancePolicyLinkAlt {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownInsurancePolicyLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Heating Breakdown Cover Insurance Product Information Document.
        /// </summary>
        public static string BundleHeatingBreakdownInsurancePolicyLinkText {
            get {
                return ResourceManager.GetString("BundleHeatingBreakdownInsurancePolicyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Heating Cover Insurance Product Information Document.
        /// </summary>
        public static string BundleHeatingCoverInsurancePolicyLinkAlt {
            get {
                return ResourceManager.GetString("BundleHeatingCoverInsurancePolicyLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up to this fixed price energy product, you are registering your interest for a smart meter. This means we may contact you in the future to discuss a smart meter installation as and when you become eligible..
        /// </summary>
        public static string BundleSmartMeter1 {
            get {
                return ResourceManager.GetString("BundleSmartMeter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We rely on a mobile phone or wireless signal to get your smart meter readings. If these fail, you’ll either need to take your own reading and send it to us, or your bills will be estimated..
        /// </summary>
        public static string BundleSmartMeter2 {
            get {
                return ResourceManager.GetString("BundleSmartMeter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call features.
        /// </summary>
        public static string CallFeaturesHeader {
            get {
                return ResourceManager.GetString("CallFeaturesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any call features you have with your current provider may be transferred to us. These features are listed in the.
        /// </summary>
        public static string CallFeaturesPara1_1 {
            get {
                return ResourceManager.GetString("CallFeaturesPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and some will involve an ongoing monthly charge. If you’d like to add or change any of these call features, please get in touch after your phone service starts..
        /// </summary>
        public static string CallFeaturesPara1_2 {
            get {
                return ResourceManager.GetString("CallFeaturesPara1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that our call packages do not allow calls to be made to premium rate numbers beginning 09..
        /// </summary>
        public static string CallFeaturesPara2 {
            get {
                return ResourceManager.GetString("CallFeaturesPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation and early termination charges.
        /// </summary>
        public static string CancellationAndEarlyTermChargeHeader {
            get {
                return ResourceManager.GetString("CancellationAndEarlyTermChargeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following charges may apply following cancellation of the broadband contract:.
        /// </summary>
        public static string CancellationAndEarlyTermChargePara1 {
            get {
                return ResourceManager.GetString("CancellationAndEarlyTermChargePara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cancel your broadband order before your service start date, there will be no charge unless you have already received your router and you do not return this to us. When you notify us of your cancellation, we will send you a prepaid postage envelope for the return of the router. Should you not return your router within 30 working days an equipment charge of £54 will be added to your account..
        /// </summary>
        public static string CancellationAndEarlyTermChargePara2 {
            get {
                return ResourceManager.GetString("CancellationAndEarlyTermChargePara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For termination at any point between the broadband service start date and the end of month 18 of the contract, there is an early termination charge of 38 pence per remaining day of your fibre broadband contract. The maximum termination charge will be £208.80. This charge is not subject to VAT..
        /// </summary>
        public static string CancellationAndEarlyTermChargePara3 {
            get {
                return ResourceManager.GetString("CancellationAndEarlyTermChargePara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUsLinkAlt {
            get {
                return ResourceManager.GetString("ContactUsLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUsLinkText {
            get {
                return ResourceManager.GetString("ContactUsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/contact-us.
        /// </summary>
        public static string ContactUsLinkUrl {
            get {
                return ResourceManager.GetString("ContactUsLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit discount.
        /// </summary>
        public static string DDHeader {
            get {
                return ResourceManager.GetString("DDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SSE Electrical Wiring Cover Insurance Product Information Document.
        /// </summary>
        public static string ElecWiringProductInfoDocumentLinkAlt {
            get {
                return ResourceManager.GetString("ElecWiringProductInfoDocumentLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Electrical Wiring Cover Insurance Product Information Document.
        /// </summary>
        public static string ElecWiringProductInfoDocumentLinkText {
            get {
                return ResourceManager.GetString("ElecWiringProductInfoDocumentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE0721_SSE_Home_Services_IPIDs_Electric_Wiring_Cover_Product_information_document.pdf.
        /// </summary>
        public static string ElecWiringProductInfoDocumentLinkUrl {
            get {
                return ResourceManager.GetString("ElecWiringProductInfoDocumentLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further information about our tariffs, please read our terms and conditions below..
        /// </summary>
        public static string FullTermsAndConditionsPara {
            get {
                return ResourceManager.GetString("FullTermsAndConditionsPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Deal.
        /// </summary>
        public static string GreenDealHeader {
            get {
                return ResourceManager.GetString("GreenDealHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Green Deal Scheme in place for your home, Green Deal charges will also apply. The estimates included in this application do not include Green Deal charges. We will write to you separately to confirm if a Green Deal charge applies..
        /// </summary>
        public static string GreenDealPara {
            get {
                return ResourceManager.GetString("GreenDealPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE Heating Breakdown Cover Insurance Product Information Document.pdf.
        /// </summary>
        public static string HeatingBreakdownCoverInsurancePolicyPdfLinkUrl {
            get {
                return ResourceManager.GetString("HeatingBreakdownCoverInsurancePolicyPdfLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE Breakdown Cover Policy Booklet.pdf.
        /// </summary>
        public static string HeatingBreakdownCoverPolicyPdfLinkUrl {
            get {
                return ResourceManager.GetString("HeatingBreakdownCoverPolicyPdfLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE0721_SSE_Home_Services_IPIDs_Heating_Cover_Product_information_document.pdf.
        /// </summary>
        public static string HeatingCoverInsurancePolicyPdfLinkUrl {
            get {
                return ResourceManager.GetString("HeatingCoverInsurancePolicyPdfLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change your mind.
        /// </summary>
        public static string IfYouChangeYourMindHeader {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel your contract without penalty within 14 days from the day you receive your Welcome pack. If we have carried out any works or you have made a claim in this 14-day cancellation period, you will be responsible for the cost incurred..
        /// </summary>
        public static string IfYouChangeYourMindPara1 {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel your contract without penalty within 14 days from the day after the date you sign up with us. We’ll include details of how to cancel when we send your confirmation of contract. Or you can get in touch using our.
        /// </summary>
        public static string IfYouChangeYourMindPara1_1 {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page..
        /// </summary>
        public static string IfYouChangeYourMindPara1_2 {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindPara1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may also cancel this cover at any time after the cancellation period, but you will be responsible to pay us for any cover provided and any fees incurred..
        /// </summary>
        public static string IfYouChangeYourMindPara2 {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll include details of how to cancel when we send your confirmation of contract. Or you can get in touch using our &lt;a href=&quot;https://sse.co.uk/help/contact-us&quot; target=&quot;_blank&quot; title=&quot;Contact us&quot;&gt;Contact us&lt;/a&gt; page..
        /// </summary>
        public static string IfYouChangeYourMindPara3 {
            get {
                return ResourceManager.GetString("IfYouChangeYourMindPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Wiring Inspection.
        /// </summary>
        public static string ImportantInformationElecWiringInspHeader {
            get {
                return ResourceManager.GetString("ImportantInformationElecWiringInspHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Wiring Cover covers your home&apos;s fixed electrical wiring system. &quot;Fixed electrical wiring system&quot; means your electrical wiring, fuse box, light fittings and switches, wall sockets and shower isolation switches. We may need to do an initial visual inspection of your fixed electrical wiring system and an earth loop impedance test. This may be necessary if your house is over 15 years old, hasn&apos;t been rewired in the last 15 years or has an old-style fuse box..
        /// </summary>
        public static string ImportantInformationElecWiringInspPara1 {
            get {
                return ResourceManager.GetString("ImportantInformationElecWiringInspPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more details, please read the insurance product information document:.
        /// </summary>
        public static string ImportantInformationElecWiringInspPara2 {
            get {
                return ResourceManager.GetString("ImportantInformationElecWiringInspPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Wiring Cover – important information.
        /// </summary>
        public static string ImportantInformationHeader {
            get {
                return ResourceManager.GetString("ImportantInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Wiring Cover – important information.
        /// </summary>
        public static string ImportantInformationHeaderAlt {
            get {
                return ResourceManager.GetString("ImportantInformationHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and labour.
        /// </summary>
        public static string ImportantInformationPartsLabourHeader {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is subject to terms and conditions found in the.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_1 {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_2 {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SSE Home Services policy booklet.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link1Alt {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link1Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Home Services Policy Booklet.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link1Text {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE Home Services Policy Booklet.pdf.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link1Url {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link1Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Insurance Product Information Document.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link2Alt {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link2Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Product Information Document.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link2Text {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE0721_SSE_Home_Services_IPIDs_Electric_Wiring_Cover_Product_information_document.pdf.
        /// </summary>
        public static string ImportantInformationPartsLabourPara1_Link2Url {
            get {
                return ResourceManager.GetString("ImportantInformationPartsLabourPara1_Link2Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you need to know before you apply.
        /// </summary>
        public static string NeedToKnowHeader {
            get {
                return ResourceManager.GetString("NeedToKnowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send your Welcome pack by email. This includes your confirmation of contract, tariff information, terms and conditions and cancellation form..
        /// </summary>
        public static string NeedToKnowPara2 {
            get {
                return ResourceManager.GetString("NeedToKnowPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we’re taking over the supply of energy from another supplier, you agree to your current supplier transferring the right for us to collect any debt you owe them (in the event we’re obliged to)..
        /// </summary>
        public static string NeedToKnowPara3 {
            get {
                return ResourceManager.GetString("NeedToKnowPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE  is now part of  the OVO family, which means some of your communications may say SSE Home Services and some may mention OVO (S) Home Services. This will not negatively impact the product or service that you will receive.  Please bear with us as we update all of our communications accordingly..
        /// </summary>
        public static string OVODisclaimerText {
            get {
                return ResourceManager.GetString("OVODisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper billing.
        /// </summary>
        public static string PaperBillingHeader {
            get {
                return ResourceManager.GetString("PaperBillingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will have paperless billing as standard. If you’d like paper billing, you can choose this option on your online account. This will add a monthly charge of £2 to your broadband and phone bill..
        /// </summary>
        public static string PaperBillingPara1 {
            get {
                return ResourceManager.GetString("PaperBillingPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is subject to terms and conditions found in the .
        /// </summary>
        public static string PartsAndLabourPara1 {
            get {
                return ResourceManager.GetString("PartsAndLabourPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and the .
        /// </summary>
        public static string PartsAndLabourPara2 {
            get {
                return ResourceManager.GetString("PartsAndLabourPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SSE Phone Product and Price Guide for the Fix and Fibre range (FF3).
        /// </summary>
        public static string PhoneGuideAlt {
            get {
                return ResourceManager.GetString("PhoneGuideAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Phone Product and Price Guide for the Fix and Fibre range (FF3).
        /// </summary>
        public static string PhoneGuideLinkText {
            get {
                return ResourceManager.GetString("PhoneGuideLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE Phone Product and Price Guide for the Fix and Fibre range (FF3).pdf.
        /// </summary>
        public static string PhoneGuideLinkUrl {
            get {
                return ResourceManager.GetString("PhoneGuideLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you sign up to one of our other fixed price tariffs, you are registering your interest for a smart meter. This means we may contact you in the future to discuss a smart meter installation as and when you become eligible..
        /// </summary>
        public static string SmartMeter2 {
            get {
                return ResourceManager.GetString("SmartMeter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We rely on a mobile phone or wireless signal to receive your readings. If these fail, your bills will be estimated..
        /// </summary>
        public static string SmartMeter3 {
            get {
                return ResourceManager.GetString("SmartMeter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart meters.
        /// </summary>
        public static string SmartMeterHeader {
            get {
                return ResourceManager.GetString("SmartMeterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Broadband Happiness Guarantee.
        /// </summary>
        public static string SSEBroadbandHappinessHeader {
            get {
                return ResourceManager.GetString("SSEBroadbandHappinessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers signing up for SSE fixed-term broadband and phone package Bundles can leave their contract without early termination charges if, within the first 60 days, they are not happy with any aspect of the service they have received, and we have been unable to fix the problem..
        /// </summary>
        public static string SSEBroadbandHappinessPara1 {
            get {
                return ResourceManager.GetString("SSEBroadbandHappinessPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Guarantee full details.
        /// </summary>
        public static string SSEBroadbandHappinessPara1_Link1Text {
            get {
                return ResourceManager.GetString("SSEBroadbandHappinessPara1_Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSE Hydro, Glasgow.
        /// </summary>
        public static string SSEHydroAlt {
            get {
                return ResourceManager.GetString("SSEHydroAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle FAQs.
        /// </summary>
        public static string SwitchFAQAccordionHeader_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQAccordionHeader_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching FAQs.
        /// </summary>
        public static string SwitchFAQAccordionHeader_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQAccordionHeader_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m already an SSE customer. Can I get a Bundle?.
        /// </summary>
        public static string SwitchFAQAccordionSubHeader1Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQAccordionSubHeader1Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m already an SSE customer. Can I get a Bundle?.
        /// </summary>
        public static string SwitchFAQSubHeader1_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader1_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should I let my current supplier know I’m switching?.
        /// </summary>
        public static string SwitchFAQSubHeader1_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader1_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should I let my current supplier know I’m switching?.
        /// </summary>
        public static string SwitchFAQSubHeader1Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader1Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our Bundles are available to new and existing SSE customers, as long as you pay by Direct Debit..
        /// </summary>
        public static string SwitchFAQSubHeader1Para_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader1Para_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you sign up, we’ll take care of everything including telling your current energy provider that you want to switch to us..
        /// </summary>
        public static string SwitchFAQSubHeader1Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader1Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long will it take to switch my utilities?.
        /// </summary>
        public static string SwitchFAQSubHeader2_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long will my switch take?.
        /// </summary>
        public static string SwitchFAQSubHeader2_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long will it take to switch my utilities?.
        /// </summary>
        public static string SwitchFAQSubHeader2Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long will my switch take?.
        /// </summary>
        public static string SwitchFAQSubHeader2Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re signed up to the Energy Switch Guarantee, so we’ll make sure we switch your gas and/or electricity supply within 21 days..
        /// </summary>
        public static string SwitchFAQSubHeader2Para_Bundle_1 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Para_Bundle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching your broadband and phone takes around 18 to 20 days..
        /// </summary>
        public static string SwitchFAQSubHeader2Para_Bundle_2 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Para_Bundle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler and heating products and Electrical Wiring Cover start on the next working day after your energy supply switches to us..
        /// </summary>
        public static string SwitchFAQSubHeader2Para_Bundle_3 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Para_Bundle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re signed up to the Energy Switch Guarantee which means switching your gas and/or electricity will take no longer than 21 days..
        /// </summary>
        public static string SwitchFAQSubHeader2Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader2Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should I let my utilities providers know that I’m switching?.
        /// </summary>
        public static string SwitchFAQSubHeader3_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when I switch?.
        /// </summary>
        public static string SwitchFAQSubHeader3_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should I let my utilities providers know that I’m switching?.
        /// </summary>
        public static string SwitchFAQSubHeader3Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when I switch?.
        /// </summary>
        public static string SwitchFAQSubHeader3Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to tell your current energy, broadband or phone providers you’re switching to us – we’ll do that for you, unless you’re with Virgin Media. If you’re a Virgin Media customer, you’ll have to contact them directly to cancel your broadband and phone service..
        /// </summary>
        public static string SwitchFAQSubHeader3Para_Bundle_1 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3Para_Bundle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your Bundle includes a boiler and heating product or Electrical Wiring Cover and you currently have a similar product with another provider, you’ll need to contact them to cancel it..
        /// </summary>
        public static string SwitchFAQSubHeader3Para_Bundle_2 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3Para_Bundle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you sign up, we’ll send your paperwork by email. Once your 14-day cooling off period has finished, we’ll ask your current energy supplier for your supply and begin your switch. Just before the switch is complete, we’ll ask you for your meter reading(s) and give these to your old supplier so they close your account on the same readings..
        /// </summary>
        public static string SwitchFAQSubHeader3Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader3Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when I sign up for a Bundle?.
        /// </summary>
        public static string SwitchFAQSubHeader4_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when I sign up for a Bundle?.
        /// </summary>
        public static string SwitchFAQSubHeader4Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you sign up, we’ll send you Welcome packs with full details about your products..
        /// </summary>
        public static string SwitchFAQSubHeader4Para_Bundle_1 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4Para_Bundle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just before we switch your gas and/or electricity supply to us, we’ll ask you for your meter readings and give these to your old supplier so they can close your account..
        /// </summary>
        public static string SwitchFAQSubHeader4Para_Bundle_2 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4Para_Bundle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your Bundle includes broadband and phone, we’ll let you know if you need an engineer to visit. Then we’ll post you a wireless broadband router. Plug it in on the day of the switch – you’re connected and ready to go!.
        /// </summary>
        public static string SwitchFAQSubHeader4Para_Bundle_3 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4Para_Bundle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For boiler and heating products and Electrical Wiring Cover, your 24/7 cover will start on the next working day after your energy supply switches to us..
        /// </summary>
        public static string SwitchFAQSubHeader4Para_Bundle_4 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader4Para_Bundle_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Bundles have a minimum term contract?.
        /// </summary>
        public static string SwitchFAQSubHeader5_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader5_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Bundles have a minimum term contract?.
        /// </summary>
        public static string SwitchFAQSubHeader5Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader5Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, all the products in our Bundles have 12-month or 18-month fixed-term contracts..
        /// </summary>
        public static string SwitchFAQSubHeader5Para_Bundle_1 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader5Para_Bundle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have to pay termination charges if you cancel a contract before the end of the term. We’ll explain the terms and conditions for each product before you sign up..
        /// </summary>
        public static string SwitchFAQSubHeader5Para_Bundle_2 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader5Para_Bundle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when my Bundle ends?.
        /// </summary>
        public static string SwitchFAQSubHeader6_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are SSE?.
        /// </summary>
        public static string SwitchFAQSubHeader6_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when my Bundle ends?.
        /// </summary>
        public static string SwitchFAQSubHeader6Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are SSE?.
        /// </summary>
        public static string SwitchFAQSubHeader6Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll pay the Bundle price for each product until your fixed-term contracts end..
        /// </summary>
        public static string SwitchFAQSubHeader6Para_Bundle_1 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Para_Bundle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the end of your contract, we’ll move you onto our Standard variable tariff for energy. But we’ll contact you before that to let you know our latest tariffs so you can review your options..
        /// </summary>
        public static string SwitchFAQSubHeader6Para_Bundle_2 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Para_Bundle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For broadband and phone and boiler and heating products, you’ll pay the standard monthly price after your fixed-term contract ends. We’ll remind you about this price change before the end of your contract..
        /// </summary>
        public static string SwitchFAQSubHeader6Para_Bundle_3 {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Para_Bundle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We first formed in 1998 when Scottish Hydro Electric merged with Southern Electric to become Scottish and Southern Energy. Later we incorporated SWALEC and Atlantic into our family and we’re now known as SSE. You may be familiar with our local brands – SSE Southern Electric, SSE Scottish Hydro and SSE SWALEC. But no matter what our name is, our primary aim is to give great customer service to our customers..
        /// </summary>
        public static string SwitchFAQSubHeader6Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader6Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a fixed price tariff?.
        /// </summary>
        public static string SwitchFAQSubHeader7_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader7_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a fixed price tariff?.
        /// </summary>
        public static string SwitchFAQSubHeader7Alt_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader7Alt_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a fixed price tariff your unit rate per kWh energy prices will stay the same over the period of your contract..
        /// </summary>
        public static string SwitchFAQSubHeader7Para_Bundle {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeader7Para_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a fixed price tariff?.
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay4_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay4_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a fixed price tariff?.
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay4Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay4Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a fixed price tariff your unit rate per kWh energy prices will stay the same over the period of your contract..
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay4Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay4Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does ‘early exit fee’ mean?.
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay5_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay5_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does ‘early exit fee’ mean?.
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay5Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay5Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of our energy plans have ‘early exit fees’. We’ll charge you a certain amount if you switch to a different energy supplier or tariff before the end of your contract. These fees are ‘per fuel’ which means there’s one for gas and one for electricity. If you have both fuels (dual fuel) with us, we’ll charge for both. All our exit fees are clearly stated..
        /// </summary>
        public static string SwitchFAQSubHeaderNonPrePay5Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderNonPrePay5Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Pay As You Go price cap?.
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay4_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay4_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Pay As You Go price cap?.
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay4Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay4Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofgem set a safeguard limit for Pay As You Go meters which reflects the cost of supplying energy. We set your actual energy prices, but must adhere to this price cap..
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay4Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay4Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a debt on my Pay As You Go meter – can I switch?.
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay5_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay5_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a debt on my Pay As You Go meter – can I switch?.
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay5Alt_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay5Alt_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may be able to switch if your debt is less than £500. The Debt Assignment Protocol allows you to change supplier and take your debt with you. It isn’t guaranteed but it could be an option if you want to switch..
        /// </summary>
        public static string SwitchFAQSubHeaderPrePay5Para_Energy {
            get {
                return ResourceManager.GetString("SwitchFAQSubHeaderPrePay5Para_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited downloads.
        /// </summary>
        public static string UnlimitedDownloadsHeader {
            get {
                return ResourceManager.GetString("UnlimitedDownloadsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited downloads are subject to our.
        /// </summary>
        public static string UnlimitedDownloadsPara1_1 {
            get {
                return ResourceManager.GetString("UnlimitedDownloadsPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your landline number.
        /// </summary>
        public static string YourLandlineNumberHeader {
            get {
                return ResourceManager.GetString("YourLandlineNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll look to move your landline number across to us, if you’ve asked us to do so. If we can’t do this, we’ll give you a new phone number. If you haven’t given us a landline number, or don’t have one, we’ll give you a new one. We’ll tell you what your number is once you’re set up..
        /// </summary>
        public static string YourLandlineNumberPara1 {
            get {
                return ResourceManager.GetString("YourLandlineNumberPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your right to change your mind.
        /// </summary>
        public static string YourRightToChangeYourMindHeader {
            get {
                return ResourceManager.GetString("YourRightToChangeYourMindHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel your agreement without penalty within 14 days from the day after the date you sign up with us. We’ll include details of how to cancel when we send your confirmation of contract. Or you can get in touch using our.
        /// </summary>
        public static string YourRightToChangeYourMindPara1_1 {
            get {
                return ResourceManager.GetString("YourRightToChangeYourMindPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page..
        /// </summary>
        public static string YourRightToChangeYourMindPara1_2 {
            get {
                return ResourceManager.GetString("YourRightToChangeYourMindPara1_2", resourceCulture);
            }
        }
    }
}
