//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvailableTariffs_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvailableTariffs_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.AvailableTariffs_Resources", typeof(AvailableTariffs_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, our Bundles aren’t currently available in your area.
        /// </summary>
        public static string AllBundlesUnavailableHeader {
            get {
                return ResourceManager.GetString("AllBundlesUnavailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you might be interested in some of our energy tariffs below. All prices on this page include VAT and any applicable discounts..
        /// </summary>
        public static string AllBundlesUnavailablePara {
            get {
                return ResourceManager.GetString("AllBundlesUnavailablePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re just checking bundle information..
        /// </summary>
        public static string BroadbandBundlePopupText {
            get {
                return ResourceManager.GetString("BroadbandBundlePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices on this page include VAT and any applicable discounts..
        /// </summary>
        public static string BundleDisclaimer {
            get {
                return ResourceManager.GetString("BundleDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start sign-up for this Bundle.
        /// </summary>
        public static string BundleSignupButtonAlt {
            get {
                return ResourceManager.GetString("BundleSignupButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        public static string BundleTabName {
            get {
                return ResourceManager.GetString("BundleTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chosen Bundle.
        /// </summary>
        public static string ChosenBundleSubHeader {
            get {
                return ResourceManager.GetString("ChosenBundleSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your chosen Bundle isn’t currently available in your area.
        /// </summary>
        public static string ChosenBundleUnavailableHeader {
            get {
                return ResourceManager.GetString("ChosenBundleUnavailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you might be interested in some of our other products below. All prices on this page include VAT and any applicable discounts..
        /// </summary>
        public static string ChosenBundleUnavailablePara {
            get {
                return ResourceManager.GetString("ChosenBundleUnavailablePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chosen tariff.
        /// </summary>
        public static string ChosenTariffHeader {
            get {
                return ResourceManager.GetString("ChosenTariffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your chosen tariff isn’t currently available in your area.
        /// </summary>
        public static string ChosenTariffNotAvailableHeader {
            get {
                return ResourceManager.GetString("ChosenTariffNotAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but based on the information provided you won’t be able to get the tariff you selected..
        /// </summary>
        public static string ChosenTariffNotAvailableMessage {
            get {
                return ResourceManager.GetString("ChosenTariffNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might also be interested in.
        /// </summary>
        public static string ChosenTariffOtherTariffsHeader {
            get {
                return ResourceManager.GetString("ChosenTariffOtherTariffsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or choose one of our other tariffs.
        /// </summary>
        public static string ChosenTariffSubHeader {
            get {
                return ResourceManager.GetString("ChosenTariffSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy prices may go up or down.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity: .
        /// </summary>
        public static string ElecLabel {
            get {
                return ResourceManager.GetString("ElecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity = {0} kWh per year.
        /// </summary>
        public static string ElectricityUsageParaghraph1SubText {
            get {
                return ResourceManager.GetString("ElectricityUsageParaghraph1SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string EnergyTabName {
            get {
                return ResourceManager.GetString("EnergyTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  per fuel early exit fee.
        /// </summary>
        public static string ExitFee {
            get {
                return ResourceManager.GetString("ExitFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes £{0} discount per year (£{1} for gas and £{1} for electricity).
        /// </summary>
        public static string FixedTariffDualFuelDiscountText {
            get {
                return ResourceManager.GetString("FixedTariffDualFuelDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes £{0} discount per year.
        /// </summary>
        public static string FixedTariffSingleFuelDiscountText {
            get {
                return ResourceManager.GetString("FixedTariffSingleFuelDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas: .
        /// </summary>
        public static string GasLabel {
            get {
                return ResourceManager.GetString("GasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas = {0} kWh per year.
        /// </summary>
        public static string GasUsageParaghraph1SubText {
            get {
                return ResourceManager.GetString("GasUsageParaghraph1SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download General Terms and Conditions for the Supply of Electricity and/or Gas.
        /// </summary>
        public static string GeneralTermsAndConditionsPDFAlt {
            get {
                return ResourceManager.GetString("GeneralTermsAndConditionsPDFAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Terms and Conditions for the Supply of Electricity and/or Gas.
        /// </summary>
        public static string GeneralTermsAndConditionsPDFText {
            get {
                return ResourceManager.GetString("GeneralTermsAndConditionsPDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quote &lt;/br&gt; for .
        /// </summary>
        public static string Header_Bundling {
            get {
                return ResourceManager.GetString("Header_Bundling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new energy tariff for .
        /// </summary>
        public static string Header_Energy {
            get {
                return ResourceManager.GetString("Header_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show less.
        /// </summary>
        public static string HideBundleDetailsHeader {
            get {
                return ResourceManager.GetString("HideBundleDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide energy tariff details.
        /// </summary>
        public static string HideTariffDetailsHeader {
            get {
                return ResourceManager.GetString("HideTariffDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The costs below are based on the usage you just gave us..
        /// </summary>
        public static string KnownUsageParagraph1 {
            get {
                return ResourceManager.GetString("KnownUsageParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close dialogue box.
        /// </summary>
        public static string ModalCloseButtonAlt {
            get {
                return ResourceManager.GetString("ModalCloseButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string MoreInfoLink {
            get {
                return ResourceManager.GetString("MoreInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No early exit fee.
        /// </summary>
        public static string NoExitFee {
            get {
                return ResourceManager.GetString("NoExitFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As we’re now part of the OVO family, we may have cheaper tariff options for you, although some may have eligibility criteria. To find out more, visit &lt;a target=&quot;_blank&quot; title=&quot;OVO Energy&quot; href=&quot;http://ovoenergy.com&quot;&gt;ovoenergy.com&lt;/a&gt; or call 0330 303 5063, &lt;a target=&quot;_blank&quot; title=&quot;Boost&quot; href =&quot;http://boostpower.co.uk&quot;&gt;boostpower.co.uk&lt;/a&gt; or call 0330 102 7517, or &lt;a href = &quot;http://sparkenergy.co.uk&quot; target=&quot;_blank&quot; title=&quot;Spark&quot;&gt;sparkenergy.co.uk&lt;/a&gt; or call 0345 034 7474..
        /// </summary>
        public static string PartnershipText {
            get {
                return ResourceManager.GetString("PartnershipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected monthly cost:.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive presale events tickets access up to 48 hours before general release.
        /// </summary>
        public static string RewardsBullet1 {
            get {
                return ResourceManager.GetString("RewardsBullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-off prizes and competitions exclusively available to our customers.
        /// </summary>
        public static string RewardsBullet2 {
            get {
                return ResourceManager.GetString("RewardsBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades to SSE lounges.
        /// </summary>
        public static string RewardsBullet3 {
            get {
                return ResourceManager.GetString("RewardsBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE customers can get these great benefits at The SSE Arena, Belfast, The SSE Arena, Wembley, and The SSE Hydro in Glasgow:.
        /// </summary>
        public static string RewardsText {
            get {
                return ResourceManager.GetString("RewardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowBundleDetailsHeader {
            get {
                return ResourceManager.GetString("ShowBundleDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show energy tariff details.
        /// </summary>
        public static string ShowTariffDetailsHeader {
            get {
                return ResourceManager.GetString("ShowTariffDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start sign-up for this tariff.
        /// </summary>
        public static string SignupButtonAlt {
            get {
                return ResourceManager.GetString("SignupButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string SignupButtonText {
            get {
                return ResourceManager.GetString("SignupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £50 electricity credit at the end of the tariff subject to your terms and conditions.
        /// </summary>
        public static string SmartTariffTILText {
            get {
                return ResourceManager.GetString("SmartTariffTILText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you’ve chosen to pay by Direct Debit, you’ll receive an annual discount for each fuel..
        /// </summary>
        public static string StandardTariffDiscountText {
            get {
                return ResourceManager.GetString("StandardTariffDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes {0} discount per year ({1} for gas and {2} for electricity).
        /// </summary>
        public static string StandardTariffDualFuelDiscountText {
            get {
                return ResourceManager.GetString("StandardTariffDualFuelDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes {0} discount per year.
        /// </summary>
        public static string StandardTariffSingleFuelDiscountText {
            get {
                return ResourceManager.GetString("StandardTariffSingleFuelDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your tariff and sign up online.
        /// </summary>
        public static string Switch1 {
            get {
                return ResourceManager.GetString("Switch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll tell your supplier you’re switching.
        /// </summary>
        public static string Switch2 {
            get {
                return ResourceManager.GetString("Switch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll ask you for meter readings and keep in touch until you’ve switched.
        /// </summary>
        public static string Switch3 {
            get {
                return ResourceManager.GetString("Switch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up – choose a Bundle with energy, plus broadband and phone, or a boiler and heating product.
        /// </summary>
        public static string SwitchBundle1 {
            get {
                return ResourceManager.GetString("SwitchBundle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit back – no need to contact your current energy or broadband provider (unless you’re with Virgin Media).
        /// </summary>
        public static string SwitchBundle2 {
            get {
                return ResourceManager.GetString("SwitchBundle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax – we’ll sort out your switch and keep you posted at every step.
        /// </summary>
        public static string SwitchBundle3 {
            get {
                return ResourceManager.GetString("SwitchBundle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save – pay less compared to buying our equivalent standalone products!.
        /// </summary>
        public static string SwitchBundle4 {
            get {
                return ResourceManager.GetString("SwitchBundle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We promise to switch your gas and electricity within 21 days. Switching your broadband and phone usually takes around 18 to 20 days. Boiler and heating products start on the next working day after your energy supply switches to us..
        /// </summary>
        public static string SwitchGuaranteeTextBundle {
            get {
                return ResourceManager.GetString("SwitchGuaranteeTextBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We promise to complete your switch in no more than 21 days..
        /// </summary>
        public static string SwitchGuaranteeTextEnergy {
            get {
                return ResourceManager.GetString("SwitchGuaranteeTextEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching your energy to SSE is easy.
        /// </summary>
        public static string SwitchHeader {
            get {
                return ResourceManager.GetString("SwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s easy to switch and save with our Bundles.
        /// </summary>
        public static string SwitchHeaderBundle {
            get {
                return ResourceManager.GetString("SwitchHeaderBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TariffDetailsHeaderAlt {
            get {
                return ResourceManager.GetString("TariffDetailsHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices on this page include VAT and any applicable discounts..
        /// </summary>
        public static string TariffDisclaimer {
            get {
                return ResourceManager.GetString("TariffDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a multi-rate electricity customer, we can now offer you a choice of tariffs without having to change your meter. Please contact our Welcomeline team on .
        /// </summary>
        public static string TariffFooter {
            get {
                return ResourceManager.GetString("TariffFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  who’ll be able to help pick the best tariff for your home..
        /// </summary>
        public static string TariffFooterLinkSuffix {
            get {
                return ResourceManager.GetString("TariffFooterLinkSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your product.
        /// </summary>
        public static string TariffSubHeader {
            get {
                return ResourceManager.GetString("TariffSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string TILFAQHeader {
            get {
                return ResourceManager.GetString("TILFAQHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional products or services included.
        /// </summary>
        public static string TILLAdditionalProductsOrServicesIncluded {
            get {
                return ResourceManager.GetString("TILLAdditionalProductsOrServicesIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts and additional charges.
        /// </summary>
        public static string TILLDiscountsAndAdditionalChargesLabel {
            get {
                return ResourceManager.GetString("TILLDiscountsAndAdditionalChargesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit fee (if you cancel this tariff 
        ///before the end date).
        /// </summary>
        public static string TILLExitFeeLabel {
            get {
                return ResourceManager.GetString("TILLExitFeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tariff Information Label.
        /// </summary>
        public static string TILLinkAlt {
            get {
                return ResourceManager.GetString("TILLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas &amp; electricity information.
        /// </summary>
        public static string TILLinkTextDual {
            get {
                return ResourceManager.GetString("TILLinkTextDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity information.
        /// </summary>
        public static string TILLinkTextElec {
            get {
                return ResourceManager.GetString("TILLinkTextElec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas information.
        /// </summary>
        public static string TILLinkTextGas {
            get {
                return ResourceManager.GetString("TILLinkTextGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string TILLPaymentMethodLabel {
            get {
                return ResourceManager.GetString("TILLPaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price guaranteed until.
        /// </summary>
        public static string TILLPriceGuaranteedUntilLabel {
            get {
                return ResourceManager.GetString("TILLPriceGuaranteedUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing charge.
        /// </summary>
        public static string TILLStandingChargeLabel {
            get {
                return ResourceManager.GetString("TILLStandingChargeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string TILLSupplierLabel {
            get {
                return ResourceManager.GetString("TILLSupplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff ends on.
        /// </summary>
        public static string TILLTariffEndsOnLabel {
            get {
                return ResourceManager.GetString("TILLTariffEndsOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff name.
        /// </summary>
        public static string TILLTariffNameLabel {
            get {
                return ResourceManager.GetString("TILLTariffNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff type.
        /// </summary>
        public static string TILLTariffTypeLabel {
            get {
                return ResourceManager.GetString("TILLTariffTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit rate off-peak.
        /// </summary>
        public static string TILLUnitRateOffPeakLabel {
            get {
                return ResourceManager.GetString("TILLUnitRateOffPeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit rate peak.
        /// </summary>
        public static string TILLUnitRatePeakLabel {
            get {
                return ResourceManager.GetString("TILLUnitRatePeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string TILNotApplicable {
            get {
                return ResourceManager.GetString("TILNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our online home is at sse.co.uk. So, the Tariff Information Label (TIL) for all our tariffs show SSE as the supplier. But the prices are also correct for our other brands SSE Southern Electric, SSE SWALEC and SSE Scottish Hydro..
        /// </summary>
        public static string TILParagraphAboveInformation {
            get {
                return ResourceManager.GetString("TILParagraphAboveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated costs include any discounts and VAT (currently 5%) and are based on current prices for the tariff shown above. The prices quoted may be different to how these are displayed on your bill. If your tariff type is Evergreen, then please note that prices are not fixed and may rise in the future..
        /// </summary>
        public static string TILParagraphUnderInformation {
            get {
                return ResourceManager.GetString("TILParagraphUnderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from supply start date.
        /// </summary>
        public static string TILPriceGuaranteedDate {
            get {
                return ResourceManager.GetString("TILPriceGuaranteedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p per day.
        /// </summary>
        public static string TILStandingCharge {
            get {
                return ResourceManager.GetString("TILStandingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a kWh (kilowatt hour)?.
        /// </summary>
        public static string TilSubHeader {
            get {
                return ResourceManager.GetString("TilSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh stands for kilowatt-hour - the unit used to measure the amount of electricity you use. One kilowatt equals 1,000 watts of electricity and will power a 40-watt light bulb for 25 hours..
        /// </summary>
        public static string TilSubHeaderParagraph {
            get {
                return ResourceManager.GetString("TilSubHeaderParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about Debt Assignment Protocol.
        /// </summary>
        public static string TILSwitchLinkAlt {
            get {
                return ResourceManager.GetString("TILSwitchLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Assignment Protocol article..
        /// </summary>
        public static string TILSwitchLinkText {
            get {
                return ResourceManager.GetString("TILSwitchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/energy/meters/pay-as-you-go/switching-with-debt.
        /// </summary>
        public static string TILSwitchLinkUrl {
            get {
                return ResourceManager.GetString("TILSwitchLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’re a Pay As You Go customer with a debt of less than £500, it’s now even easier to switch. The Debt Assignment Protocol allows you to change supplier and take your debt with you. If your current energy supplier successfully objects to you moving supply because of your debt balance the Debt Assignment Protocol is activated, allowing the switch to continue. It isn’t guaranteed, but it could be an option if you want to switch. To switch your supply, we’ll need to exchange your account details and debt i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TILSwitchParagraph {
            get {
                return ResourceManager.GetString("TILSwitchParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I switch supplier with a debt on my Pay As You Go meter?.
        /// </summary>
        public static string TILSwitchSubHeader {
            get {
                return ResourceManager.GetString("TILSwitchSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from supply start date.
        /// </summary>
        public static string TILTariffEndDate {
            get {
                return ResourceManager.GetString("TILTariffEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date.
        /// </summary>
        public static string TILTariffNoEndDate {
            get {
                return ResourceManager.GetString("TILTariffNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p per kWh.
        /// </summary>
        public static string TILUnitRate {
            get {
                return ResourceManager.GetString("TILUnitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit rate.
        /// </summary>
        public static string TILUnitRateLabel {
            get {
                return ResourceManager.GetString("TILUnitRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to energy – Choose your tariff - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The costs below are based on the estimated usage we worked out from the answers you gave us about your property. We estimate you’ll use: &lt;strong&gt; {0} Electricity day = {1} kWh per year  &amp;nbsp; Electricity night = {2} kWh per year&lt;/strong&gt;.&lt;br/&gt;These figures are based on 58% usage during the day and 42% usage at night..
        /// </summary>
        public static string UnknownUsageE7Paragraph1 {
            get {
                return ResourceManager.GetString("UnknownUsageE7Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The costs below are based on the estimated usage we worked out from the answers you gave us about your property. We estimate you’ll use:  &lt;strong&gt; {0} &lt;/strong&gt;..
        /// </summary>
        public static string UnknownUsageParagraph1 {
            get {
                return ResourceManager.GetString("UnknownUsageParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK-based call centres.
        /// </summary>
        public static string USP1 {
            get {
                return ResourceManager.GetString("USP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread the cost of your energy and save money when you pay by Direct Debit*.
        /// </summary>
        public static string USP2 {
            get {
                return ResourceManager.GetString("USP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get access to presale tickets and access to big events with SSE Reward.
        /// </summary>
        public static string USP3 {
            get {
                return ResourceManager.GetString("USP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millions of customers trust us with their energy supply.
        /// </summary>
        public static string USP4 {
            get {
                return ResourceManager.GetString("USP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose SSE for your gas and electricity?.
        /// </summary>
        public static string USPHeader {
            get {
                return ResourceManager.GetString("USPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAllTabName {
            get {
                return ResourceManager.GetString("ViewAllTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That’s .
        /// </summary>
        public static string YearCostPrefix {
            get {
                return ResourceManager.GetString("YearCostPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a year.
        /// </summary>
        public static string YearCostSuffix {
            get {
                return ResourceManager.GetString("YearCostSuffix", resourceCulture);
            }
        }
    }
}
