//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Extras_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Extras_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.Extras_Resources", typeof(Extras_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Bundle.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this Extra to your Bundle.
        /// </summary>
        public static string AddButtonTextAlt {
            get {
                return ResourceManager.GetString("AddButtonTextAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a little Extra.
        /// </summary>
        public static string BannerHeader {
            get {
                return ResourceManager.GetString("BannerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your Bundle with an optional Extra.
        /// </summary>
        public static string BannerPara {
            get {
                return ResourceManager.GetString("BannerPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your home’s fixed electrical wiring lets you down, we’re here to help..
        /// </summary>
        public static string ElecWiringCoverDescription {
            get {
                return ResourceManager.GetString("ElecWiringCoverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour emergency repairs, parts and labour included, from fuse boxes to shower switches.
        /// </summary>
        public static string ElecWiringCoverGet1 {
            get {
                return ResourceManager.GetString("ElecWiringCoverGet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-month contract with cover starting the next working day after you sign up.
        /// </summary>
        public static string ElecWiringCoverGet2 {
            get {
                return ResourceManager.GetString("ElecWiringCoverGet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Electrical Wiring Cover Insurance Product Information Document.
        /// </summary>
        public static string ElecWiringPdfLinkAlt {
            get {
                return ResourceManager.GetString("ElecWiringPdfLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Electrical Wiring Cover Insurance Product Information.
        /// </summary>
        public static string ElecWiringPdfLinkText {
            get {
                return ResourceManager.GetString("ElecWiringPdfLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE0721_SSE_Home_Services_IPIDs_Electric_Wiring_Cover_Product_information_document.pdf.
        /// </summary>
        public static string ElecWiringPdfLinkUrl {
            get {
                return ResourceManager.GetString("ElecWiringPdfLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string ExtrasAddedTxt {
            get {
                return ResourceManager.GetString("ExtrasAddedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string ExtrasHeader {
            get {
                return ResourceManager.GetString("ExtrasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for a Bundle – Choose an Extra – SSE.
        /// </summary>
        public static string ExtrasPageTitle {
            get {
                return ResourceManager.GetString("ExtrasPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Home Services Policy Booklet.
        /// </summary>
        public static string HomeServicesPolicyLinkAlt {
            get {
                return ResourceManager.GetString("HomeServicesPolicyLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Home Services Policy Booklet.
        /// </summary>
        public static string HomeServicesPolicyLinkText {
            get {
                return ResourceManager.GetString("HomeServicesPolicyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Areas/Common/Content/PDFs/SSE0786_SSE_Home_Services_Policy_Booklet_Update_23_11_18.pdf.
        /// </summary>
        public static string HomeServicesPolicyLinkUrl {
            get {
                return ResourceManager.GetString("HomeServicesPolicyLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Electrical Wiring Cover includes 20% VAT and Insurance Premium Tax. Parts and labour are subject to the terms and conditions found in the.
        /// </summary>
        public static string ImportantInfoElecWringPara1 {
            get {
                return ResourceManager.GetString("ImportantInfoElecWringPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and the .
        /// </summary>
        public static string ImportantInfoElecWringPara2 {
            get {
                return ResourceManager.GetString("ImportantInfoElecWringPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . You may require an initial inspection if your house is older than 15 years old, has not been rewired in the last 15 years, or has an old-style fuse box..
        /// </summary>
        public static string ImportantInfoElecWringPara3 {
            get {
                return ResourceManager.GetString("ImportantInfoElecWringPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Bundle.
        /// </summary>
        public static string ModalAddButtonText {
            get {
                return ResourceManager.GetString("ModalAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Bundle.
        /// </summary>
        public static string ModalRemoveButtonText {
            get {
                return ResourceManager.GetString("ModalRemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View product details.
        /// </summary>
        public static string MoreDetailsLinkAlt {
            get {
                return ResourceManager.GetString("MoreDetailsLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string MoreDetailsLinkTxt {
            get {
                return ResourceManager.GetString("MoreDetailsLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Extra from your Bundle.
        /// </summary>
        public static string RemoveButtonAlt {
            get {
                return ResourceManager.GetString("RemoveButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Bundle.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0}, you&apos;ll get:.
        /// </summary>
        public static string YouWillGetHeaderText {
            get {
                return ResourceManager.GetString("YouWillGetHeaderText", resourceCulture);
            }
        }
    }
}
