//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fallout_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fallout_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.Fallout_Resources", typeof(Fallout_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Area not covered – SSE.
        /// </summary>
        public static string AreaNotCoveredTitle {
            get {
                return ResourceManager.GetString("AreaNotCoveredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to find out more about the products available to you..
        /// </summary>
        public static string CantFindPricesContactBodyPost {
            get {
                return ResourceManager.GetString("CantFindPricesContactBodyPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call us on.
        /// </summary>
        public static string CantFindPricesContactBodyPre {
            get {
                return ResourceManager.GetString("CantFindPricesContactBodyPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Can’t find prices – SSE.
        /// </summary>
        public static string CantFindPricesEnergyTitle {
            get {
                return ResourceManager.GetString("CantFindPricesEnergyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we need more information to find the prices for your postcode.
        /// </summary>
        public static string CantFindPricesHeader {
            get {
                return ResourceManager.GetString("CantFindPricesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our energy prices – Can’t find prices - SSE.
        /// </summary>
        public static string CantFindPricesOurPricesTitle {
            get {
                return ResourceManager.GetString("CantFindPricesOurPricesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and we will try to get your order complete and get you up and running as soon as possible..
        /// </summary>
        public static string Contact2Body {
            get {
                return ResourceManager.GetString("Contact2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call us on .
        /// </summary>
        public static string Contact2Header {
            get {
                return ResourceManager.GetString("Contact2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll help you pick the best tariff for your home..
        /// </summary>
        public static string ContactBody {
            get {
                return ResourceManager.GetString("ContactBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to finish signing up over the phone..
        /// </summary>
        public static string ContactBody2 {
            get {
                return ResourceManager.GetString("ContactBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact our Welcomeline team on .
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0345 071 7972..
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0345 026 7058.
        /// </summary>
        public static string ContactNumber2 {
            get {
                return ResourceManager.GetString("ContactNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0345 071 7945.
        /// </summary>
        public static string ContactNumber3 {
            get {
                return ResourceManager.GetString("ContactNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:0345 071 7972.
        /// </summary>
        public static string ContactNumberUrl {
            get {
                return ResourceManager.GetString("ContactNumberUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:0345 026 7058.
        /// </summary>
        public static string ContactNumberUrl2 {
            get {
                return ResourceManager.GetString("ContactNumberUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, our energy tariffs are temporarily unavailable.
        /// </summary>
        public static string EnergyUnavailableHeader {
            get {
                return ResourceManager.GetString("EnergyUnavailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re working to restore the service as soon as possible. Please try again later..
        /// </summary>
        public static string EnergyUnavailableParagraph {
            get {
                return ResourceManager.GetString("EnergyUnavailableParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy unavailable.
        /// </summary>
        public static string EnergyUnavailableTitle {
            get {
                return ResourceManager.GetString("EnergyUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because your meter type is different from what we’ve found for your property, we can’t sign you up for energy at this time. Please contact your current supplier to check your meter details..
        /// </summary>
        public static string IncorrectMeterBody {
            get {
                return ResourceManager.GetString("IncorrectMeterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can’t sign you up for energy.
        /// </summary>
        public static string IncorrectMeterHeader {
            get {
                return ResourceManager.GetString("IncorrectMeterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Meter details don’t match – SSE.
        /// </summary>
        public static string IncorrectMeterTitle {
            get {
                return ResourceManager.GetString("IncorrectMeterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can’t confirm your bank details, so you won’t be able to complete your order online..
        /// </summary>
        public static string InvalidBankDetailsBody {
            get {
                return ResourceManager.GetString("InvalidBankDetailsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call us to complete your order.
        /// </summary>
        public static string InvalidBankDetailsHeader {
            get {
                return ResourceManager.GetString("InvalidBankDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and we’ll finish your order over the phone..
        /// </summary>
        public static string InvalidBankDetailsLinkSuffix {
            get {
                return ResourceManager.GetString("InvalidBankDetailsLinkSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Cannot confirm bank details - SSE.
        /// </summary>
        public static string InvalidBankDetailsTitle {
            get {
                return ResourceManager.GetString("InvalidBankDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to a guide to switching your energy supplier.
        /// </summary>
        public static string Link2Alt {
            get {
                return ResourceManager.GetString("Link2Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching your gas and electricity.
        /// </summary>
        public static string Link2Text {
            get {
                return ResourceManager.GetString("Link2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/energy/switching.
        /// </summary>
        public static string Link2Url {
            get {
                return ResourceManager.GetString("Link2Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to energy saving tips and advice.
        /// </summary>
        public static string Link3Alt {
            get {
                return ResourceManager.GetString("Link3Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy efficiency and saving advice.
        /// </summary>
        public static string Link3Text {
            get {
                return ResourceManager.GetString("Link3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/energy/energy-efficiency-and-saving.
        /// </summary>
        public static string Link3Url {
            get {
                return ResourceManager.GetString("Link3Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to find out more about smart meters.
        /// </summary>
        public static string Link4Alt {
            get {
                return ResourceManager.GetString("Link4Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing smart meters.
        /// </summary>
        public static string Link4Text {
            get {
                return ResourceManager.GetString("Link4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/energy/smart-meters.
        /// </summary>
        public static string Link4Url {
            get {
                return ResourceManager.GetString("Link4Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to find out more about your energy supplier.
        /// </summary>
        public static string Link5Alt {
            get {
                return ResourceManager.GetString("Link5Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your gas and electricity supplier.
        /// </summary>
        public static string Link5Text {
            get {
                return ResourceManager.GetString("Link5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/energy/who-supplies-gas-and-electricity.
        /// </summary>
        public static string Link5Url {
            get {
                return ResourceManager.GetString("Link5Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to a guide to gas and electricity meters.
        /// </summary>
        public static string Link6Alt {
            get {
                return ResourceManager.GetString("Link6Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About gas and electricity meters.
        /// </summary>
        public static string Link6Text {
            get {
                return ResourceManager.GetString("Link6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/energy/gas-and-electricity-meters.
        /// </summary>
        public static string Link6Url {
            get {
                return ResourceManager.GetString("Link6Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our electric heating section.
        /// </summary>
        public static string LinkAlt {
            get {
                return ResourceManager.GetString("LinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy help.
        /// </summary>
        public static string linkHeader {
            get {
                return ResourceManager.GetString("linkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric tariffs and heating help.
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sse.co.uk/help/electric-heating.
        /// </summary>
        public static string LinkUrl {
            get {
                return ResourceManager.GetString("LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But as a multi-rate electricity customer we can still offer you a choice of tariffs without having to change your meter..
        /// </summary>
        public static string OtherMeterTypeBody {
            get {
                return ResourceManager.GetString("OtherMeterTypeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can’t sign you up online.
        /// </summary>
        public static string OtherMeterTypeHeader {
            get {
                return ResourceManager.GetString("OtherMeterTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Other meter type - SSE.
        /// </summary>
        public static string OtherMeterTypeTitle {
            get {
                return ResourceManager.GetString("OtherMeterTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can’t sign you up online.
        /// </summary>
        public static string SmartPayGoHeader {
            get {
                return ResourceManager.GetString("SmartPayGoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may lose your smart and prepayment functions that you currently have with you smart Pay As You Go (prepayment) meter..
        /// </summary>
        public static string SmartPayGoParagraph {
            get {
                return ResourceManager.GetString("SmartPayGoParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy –Smart Pay As You Go meter - SSE.
        /// </summary>
        public static string SmartPayGoTitle {
            get {
                return ResourceManager.GetString("SmartPayGoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you can’t complete your order online today..
        /// </summary>
        public static string UnableToCompleteBody {
            get {
                return ResourceManager.GetString("UnableToCompleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can’t sign you up online.
        /// </summary>
        public static string UnableToCompleteHeader {
            get {
                return ResourceManager.GetString("UnableToCompleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for energy – Unable to complete order online – SSE.
        /// </summary>
        public static string UnableToCompleteTitle {
            get {
                return ResourceManager.GetString("UnableToCompleteTitle", resourceCulture);
            }
        }
    }
}
