//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeterType_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeterType_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.MeterType_Resources", typeof(MeterType_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of electricity meter do you have?.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most people have a standard electricity meter. Economy 7 and other types of meter are usually only in properties with all-electric heating..
        /// </summary>
        public static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the option to select standard as your electricity meter type..
        /// </summary>
        public static string RadioAriaDescription1 {
            get {
                return ResourceManager.GetString("RadioAriaDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the option to select Economy 7 as your meter type..
        /// </summary>
        public static string RadioAriaDescription2 {
            get {
                return ResourceManager.GetString("RadioAriaDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the option to select other as your meter type..
        /// </summary>
        public static string RadioAriaDescription3 {
            get {
                return ResourceManager.GetString("RadioAriaDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your meter has one reading and you pay one rate..
        /// </summary>
        public static string RadioDescription1 {
            get {
                return ResourceManager.GetString("RadioDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your meter has two readings, one for day and one for night. You pay two different rates..
        /// </summary>
        public static string RadioDescription2 {
            get {
                return ResourceManager.GetString("RadioDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Economy 10, Superdeal, Flexiheat, Total Living Control, or two electricity meters. You could also have a meter type not listed here..
        /// </summary>
        public static string RadioDescription3 {
            get {
                return ResourceManager.GetString("RadioDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard meter.
        /// </summary>
        public static string RadioHeading1 {
            get {
                return ResourceManager.GetString("RadioHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy 7.
        /// </summary>
        public static string RadioHeading2 {
            get {
                return ResourceManager.GetString("RadioHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string RadioHeading3 {
            get {
                return ResourceManager.GetString("RadioHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for Energy – Select meter type - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
