//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurPrices_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurPrices_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.OurPrices_Resources", typeof(OurPrices_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our energy prices – Area not covered - SSE.
        /// </summary>
        public static string AreaNotCoveredTitle {
            get {
                return ResourceManager.GetString("AreaNotCoveredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the availability of this tariff.
        /// </summary>
        public static string CheckAvailabilityLinkAlt {
            get {
                return ResourceManager.GetString("CheckAvailabilityLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability.
        /// </summary>
        public static string CheckAvailabilityLinkText {
            get {
                return ResourceManager.GetString("CheckAvailabilityLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayLabel {
            get {
                return ResourceManager.GetString("DayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me all….
        /// </summary>
        public static string FuelCategoryLabel {
            get {
                return ResourceManager.GetString("FuelCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your postcode.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick to include 5% VAT in prices.
        /// </summary>
        public static string IncludeVATCheckboxAlt {
            get {
                return ResourceManager.GetString("IncludeVATCheckboxAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include 5% VAT in prices.
        /// </summary>
        public static string IncludeVATCheckboxLabel {
            get {
                return ResourceManager.GetString("IncludeVATCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string NightLabel {
            get {
                return ResourceManager.GetString("NightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0}-{1} of {2}.
        /// </summary>
        public static string PagingText {
            get {
                return ResourceManager.GetString("PagingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll use your postcode to find gas and/or electricity tariff prices in your area. This includes multi-rate electricity meters like Economy 7. Some available tariffs can’t be bought online. You’ll also find energy prices for tariffs no longer for sale..
        /// </summary>
        public static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment and billing method.
        /// </summary>
        public static string PaymentMethodLabel {
            get {
                return ResourceManager.GetString("PaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pence per day.
        /// </summary>
        public static string PencePerDayLabel {
            get {
                return ResourceManager.GetString("PencePerDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pence per kWh.
        /// </summary>
        public static string PencePerkWhLabel {
            get {
                return ResourceManager.GetString("PencePerkWhLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing charge.
        /// </summary>
        public static string StandingChargeLabel {
            get {
                return ResourceManager.GetString("StandingChargeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View prices in your area.
        /// </summary>
        public static string SubmitButtonAlt {
            get {
                return ResourceManager.GetString("SubmitButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View tariffs.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff information.
        /// </summary>
        public static string TariffInformationLabel {
            get {
                return ResourceManager.GetString("TariffInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to see?.
        /// </summary>
        public static string TariffsPageBoxText {
            get {
                return ResourceManager.GetString("TariffsPageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Prices.
        /// </summary>
        public static string TariffsPageHeader {
            get {
                return ResourceManager.GetString("TariffsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are a list of tariffs and prices available in your area. Use the drop-down menus to see tariffs for different fuel or meter types, and those that are no longer for sale..
        /// </summary>
        public static string TariffsPageParagraph {
            get {
                return ResourceManager.GetString("TariffsPageParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our energy prices – View prices and tariffs - SSE.
        /// </summary>
        public static string TariffsPageTitle {
            get {
                return ResourceManager.GetString("TariffsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that are....
        /// </summary>
        public static string TariffStatusLabel {
            get {
                return ResourceManager.GetString("TariffStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIL.
        /// </summary>
        public static string TILLabel {
            get {
                return ResourceManager.GetString("TILLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the Tariff Information Label for this tariff and payment method.
        /// </summary>
        public static string TILLinkAlt {
            get {
                return ResourceManager.GetString("TILLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View TIL.
        /// </summary>
        public static string TILLinkText {
            get {
                return ResourceManager.GetString("TILLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our energy prices – Enter your postcode - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Rate.
        /// </summary>
        public static string UnitRateLabel {
            get {
                return ResourceManager.GetString("UnitRateLabel", resourceCulture);
            }
        }
    }
}
