//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Summary_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summary_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.Summary_Resources", typeof(Summary_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your Bundle product.
        /// </summary>
        public static string AboutYourBundleHeader {
            get {
                return ResourceManager.GetString("AboutYourBundleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account holders.
        /// </summary>
        public static string AccHolderLabel {
            get {
                return ResourceManager.GetString("AccHolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string AccNumberLabel {
            get {
                return ResourceManager.GetString("AccNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you eligible?.
        /// </summary>
        public static string AreYouEligibleForHomeServicesHeader {
            get {
                return ResourceManager.GetString("AreYouEligibleForHomeServicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change bank details.
        /// </summary>
        public static string BankDetailsEditAlt {
            get {
                return ResourceManager.GetString("BankDetailsEditAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank details.
        /// </summary>
        public static string BankDetailsHeader {
            get {
                return ResourceManager.GetString("BankDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to continue and change your bank details.
        /// </summary>
        public static string BankDetailsModalButtonAlt {
            get {
                return ResourceManager.GetString("BankDetailsModalButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change bank details.
        /// </summary>
        public static string BankDetailsModalButtonText {
            get {
                return ResourceManager.GetString("BankDetailsModalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going back to change your bank or payment details will clear all your Direct Debit information so you’ll need to enter it again..
        /// </summary>
        public static string BankDetailsModalMessage {
            get {
                return ResourceManager.GetString("BankDetailsModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing method.
        /// </summary>
        public static string BillingMethodHeader {
            get {
                return ResourceManager.GetString("BillingMethodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paperless.
        /// </summary>
        public static string BillingMethodType {
            get {
                return ResourceManager.GetString("BillingMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband &amp; Phone details and T&amp;Cs.
        /// </summary>
        public static string BroadbandAndPhoneHeader {
            get {
                return ResourceManager.GetString("BroadbandAndPhoneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband &amp; Phone details.
        /// </summary>
        public static string BroadbandAndPhoneHeaderAlt {
            get {
                return ResourceManager.GetString("BroadbandAndPhoneHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estimated annual {0} costs will be {1}..
        /// </summary>
        public static string BundleDisclaimer_Annual {
            get {
                return ResourceManager.GetString("BundleDisclaimer_Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} a month ({1} over 18 months). Saving is based on {2} discount for 18 months for Fibre broadband (18 x {3} = {4}), when compared to buying Unlimited Fibre, our equivalent standalone broadband product (£22 per month). .
        /// </summary>
        public static string BundleDisclaimer_Broadband {
            get {
                return ResourceManager.GetString("BundleDisclaimer_Broadband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} a month ({1} over 18 months). Saving is based on {0} discount for 18 months for Fibre Plus broadband (18 x {0} = {1}), when compared to buying Unlimited Fibre Plus, our equivalent standalone broadband product (£26 per month). .
        /// </summary>
        public static string BundleDisclaimer_BroadbandPlus {
            get {
                return ResourceManager.GetString("BundleDisclaimer_BroadbandPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  That’s {0} for gas and {1} for electricity..
        /// </summary>
        public static string BundleDisclaimer_DualFuel {
            get {
                return ResourceManager.GetString("BundleDisclaimer_DualFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your choice of tariff.
        /// </summary>
        public static string ChangeTariffLinkAlt {
            get {
                return ResourceManager.GetString("ChangeTariffLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ChangeTariffLinkText {
            get {
                return ResourceManager.GetString("ChangeTariffLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree to these terms and conditions and other product details above?.
        /// </summary>
        public static string CheckboxLegend {
            get {
                return ResourceManager.GetString("CheckboxLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check.
        /// </summary>
        public static string CreditCheckHeader {
            get {
                return ResourceManager.GetString("CreditCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to view Experian website.
        /// </summary>
        public static string CreditCheckLinkAlt {
            get {
                return ResourceManager.GetString("CreditCheckLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may also be a requirement to take a security deposit..
        /// </summary>
        public static string CreditCheckLinkSuffix {
            get {
                return ResourceManager.GetString("CreditCheckLinkSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explained in more detail here..
        /// </summary>
        public static string CreditCheckLinkText {
            get {
                return ResourceManager.GetString("CreditCheckLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.experian.co.uk/crain/index.html.
        /// </summary>
        public static string CreditCheckLinkUrl {
            get {
                return ResourceManager.GetString("CreditCheckLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to process your application, we will supply your personal information to credit reference agencies (CRAs) and they will give us information about you – such as your financial history. We do this to assess creditworthiness and product suitability, check your identity, manage your account, trace and recover debts and prevent criminal activity. We will also continue to exchange information about you with CRAs on an ongoing basis, including about your settled accounts and any debts not fully repaid on  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreditCheckParagraph {
            get {
                return ResourceManager.GetString("CreditCheckParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit calculation.
        /// </summary>
        public static string DDCalculationHeader {
            get {
                return ResourceManager.GetString("DDCalculationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We work out your monthly payment by dividing your Personal Projection by 12 and rounding it up to the nearest pound. Your Direct Debit will be taken from your bank account on the date shown..
        /// </summary>
        public static string DDCalculationParagraph {
            get {
                return ResourceManager.GetString("DDCalculationParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit discount.
        /// </summary>
        public static string DDHeader_BroadbandBundle {
            get {
                return ResourceManager.GetString("DDHeader_BroadbandBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit or standing order discount.
        /// </summary>
        public static string DDHeader_Energy {
            get {
                return ResourceManager.GetString("DDHeader_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print {0} Direct Debit instruction.
        /// </summary>
        public static string DDMandateLinkAltText {
            get {
                return ResourceManager.GetString("DDMandateLinkAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print {0} Direct Debit instruction.
        /// </summary>
        public static string DDMandateLinkText {
            get {
                return ResourceManager.GetString("DDMandateLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your details.
        /// </summary>
        public static string DetailsAccordionAlt {
            get {
                return ResourceManager.GetString("DetailsAccordionAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details.
        /// </summary>
        public static string DetailsAccordionHeader {
            get {
                return ResourceManager.GetString("DetailsAccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLightboxText {
            get {
                return ResourceManager.GetString("EditLightboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string ElecMeterLabel {
            get {
                return ResourceManager.GetString("ElecMeterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy details and T&amp;Cs.
        /// </summary>
        public static string EnergyDetailsAccordionHeader {
            get {
                return ResourceManager.GetString("EnergyDetailsAccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estimated annual energy costs will be {0}. That’s {1} a year for gas and {2} a year for electricity..
        /// </summary>
        public static string EnergyDisclaimerTextDual {
            get {
                return ResourceManager.GetString("EnergyDisclaimerTextDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estimated annual electricity costs will be {0}..
        /// </summary>
        public static string EnergyDisclaimerTextElectricityOnly {
            get {
                return ResourceManager.GetString("EnergyDisclaimerTextElectricityOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estimated annual gas costs will be {0}..
        /// </summary>
        public static string EnergyDisclaimerTextGasOnly {
            get {
                return ResourceManager.GetString("EnergyDisclaimerTextGasOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Extra.
        /// </summary>
        public static string ExtraPromptNo {
            get {
                return ResourceManager.GetString("ExtraPromptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this Extra.
        /// </summary>
        public static string ExtraPromptNoAlt {
            get {
                return ResourceManager.GetString("ExtraPromptNoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to remove this Extra.
        /// </summary>
        public static string ExtraPromptYesAlt {
            get {
                return ResourceManager.GetString("ExtraPromptYesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll soon be enjoying your superfast fibre broadband.
        /// </summary>
        public static string FixNFibrePlusSidebarText {
            get {
                return ResourceManager.GetString("FixNFibrePlusSidebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll soon be enjoying your high-speed fibre broadband.
        /// </summary>
        public static string FixNFibreSidebarText {
            get {
                return ResourceManager.GetString("FixNFibreSidebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown details and T&amp;Cs.
        /// </summary>
        public static string FixNProtectAccordionHeader {
            get {
                return ResourceManager.GetString("FixNProtectAccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Heating Breakdown Cover.
        /// </summary>
        public static string FixNProtectCoverName {
            get {
                return ResourceManager.GetString("FixNProtectCoverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Breakdown Direct Debit instruction.
        /// </summary>
        public static string FixNProtectDDGuaranteePDFLinkAlt {
            get {
                return ResourceManager.GetString("FixNProtectDDGuaranteePDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Breakdown Direct Debit instruction.
        /// </summary>
        public static string FixNProtectDDGuaranteePDFLinkText {
            get {
                return ResourceManager.GetString("FixNProtectDDGuaranteePDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Breakdown &amp; Electrical Wiring Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectElectricalWiringDDGuaranteePDFLinkAlt {
            get {
                return ResourceManager.GetString("FixNProtectElectricalWiringDDGuaranteePDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Breakdown &amp; Electrical Wiring Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectElectricalWiringDDGuaranteePDFLinkText {
            get {
                return ResourceManager.GetString("FixNProtectElectricalWiringDDGuaranteePDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover details and T&amp;Cs.
        /// </summary>
        public static string FixNProtectPlusAccordionHeader {
            get {
                return ResourceManager.GetString("FixNProtectPlusAccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Heating Cover.
        /// </summary>
        public static string FixNProtectPlusCoverName {
            get {
                return ResourceManager.GetString("FixNProtectPlusCoverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectPlusDDGuaranteePDFLinkAlt {
            get {
                return ResourceManager.GetString("FixNProtectPlusDDGuaranteePDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectPlusDDGuaranteePDFLinkText {
            get {
                return ResourceManager.GetString("FixNProtectPlusDDGuaranteePDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Cover &amp; Electrical Wiring Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectPlusElectricalWiringDDGuaranteePDFLinkAlt {
            get {
                return ResourceManager.GetString("FixNProtectPlusElectricalWiringDDGuaranteePDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Heating Cover &amp; Electrical Wiring Cover Direct Debit instruction.
        /// </summary>
        public static string FixNProtectPlusElectricalWiringDDGuaranteePDFLinkText {
            get {
                return ResourceManager.GetString("FixNProtectPlusElectricalWiringDDGuaranteePDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Home Services Policy Booklet.
        /// </summary>
        public static string FixNProtectPlusPolicyBookletName {
            get {
                return ResourceManager.GetString("FixNProtectPlusPolicyBookletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Breakdown Cover Policy Booklet.
        /// </summary>
        public static string FixNProtectPolicyBookletName {
            get {
                return ResourceManager.GetString("FixNProtectPolicyBookletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string GasMeterLabel {
            get {
                return ResourceManager.GetString("GasMeterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re almost done.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Heating Breakdown cover will start on the next working day after your energy switch date.
        /// </summary>
        public static string HesBundleBoilerCoverSidebarText {
            get {
                return ResourceManager.GetString("HesBundleBoilerCoverSidebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your heating cover will start on the next working day after your energy switch date.
        /// </summary>
        public static string HesBundlePlusBoilerCoverSidebarText {
            get {
                return ResourceManager.GetString("HesBundlePlusBoilerCoverSidebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} a month ({1} over 12 months). Saving is based on Heating Breakdown being free for 12 months compared to the standard price when bought separately ({2} a month): {2} x 12 = {3}..
        /// </summary>
        public static string HesDisclaimerText1 {
            get {
                return ResourceManager.GetString("HesDisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your estimated annual energy costs will be {0}. That’s {1} for gas and {2} for electricity..
        /// </summary>
        public static string HesDisclaimerTextDualFuel {
            get {
                return ResourceManager.GetString("HesDisclaimerTextDualFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your estimated annual gas costs will be {0}..
        /// </summary>
        public static string HesDisclaimerTextSingleFuel {
            get {
                return ResourceManager.GetString("HesDisclaimerTextSingleFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} a month ({1} over 12 months). Saving is based on a {0} discount for 12 months for Heating Cover (12 x {0} = {1}), when compared to buying Heating Cover separately ({2} per month)..
        /// </summary>
        public static string HesPlusDisclaimerText1 {
            get {
                return ResourceManager.GetString("HesPlusDisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to see how we get your meter details.
        /// </summary>
        public static string HowDoWeKnowLinkAlt {
            get {
                return ResourceManager.GetString("HowDoWeKnowLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we know this?.
        /// </summary>
        public static string HowDoWeKnowLinkText {
            get {
                return ResourceManager.GetString("HowDoWeKnowLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter details.
        /// </summary>
        public static string MeterDetailsHeader {
            get {
                return ResourceManager.GetString("MeterDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to confirm your meter details don’t match.
        /// </summary>
        public static string MeterDetailsModalButtonAlt {
            get {
                return ResourceManager.GetString("MeterDetailsModalButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  My details don’t match.
        /// </summary>
        public static string MeterDetailsModalButtonText {
            get {
                return ResourceManager.GetString("MeterDetailsModalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to close this dialogue box and return to the summary page.
        /// </summary>
        public static string MeterDetailsModalCancelButtonAlt {
            get {
                return ResourceManager.GetString("MeterDetailsModalCancelButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My details match.
        /// </summary>
        public static string MeterDetailsModalCancelButtonText {
            get {
                return ResourceManager.GetString("MeterDetailsModalCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your meter details are incorrect, you won’t be able to sign up with us. Please check using the meter serial numbers below..
        /// </summary>
        public static string MeterDetailsModalMessage {
            get {
                return ResourceManager.GetString("MeterDetailsModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string MethodLabel {
            get {
                return ResourceManager.GetString("MethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to close this dialogue box and return to the order summary page.
        /// </summary>
        public static string ModalCancelButtonAlt {
            get {
                return ResourceManager.GetString("ModalCancelButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalCancelButtonText {
            get {
                return ResourceManager.GetString("ModalCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close dialogue box.
        /// </summary>
        public static string ModalCloseButtonAlt {
            get {
                return ResourceManager.GetString("ModalCloseButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we know this?.
        /// </summary>
        public static string ModalMeterDetailsHeader {
            get {
                return ResourceManager.GetString("ModalMeterDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve used national metering databases to find the meter details for your address..
        /// </summary>
        public static string ModalMeterDetailsMessage {
            get {
                return ResourceManager.GetString("ModalMeterDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  meter (non-smart).
        /// </summary>
        public static string NonSmart {
            get {
                return ResourceManager.GetString("NonSmart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paperless billing.
        /// </summary>
        public static string PaperlessBillingHeader {
            get {
                return ResourceManager.GetString("PaperlessBillingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will have paperless billing as standard. If you’d like paper billing, you can .
        /// </summary>
        public static string PaperlessBillingPara1 {
            get {
                return ResourceManager.GetString("PaperlessBillingPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and labour.
        /// </summary>
        public static string PartsAndLabourHeader {
            get {
                return ResourceManager.GetString("PartsAndLabourHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay As You Go.
        /// </summary>
        public static string PayAsYouGoHeader {
            get {
                return ResourceManager.GetString("PayAsYouGoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’re a Pay As You Go customer with a debt of less than £500, it’s now even easier to switch. The Debt Assignment Protocol allows you to change supplier and take your debt with you. If your current energy supplier successfully objects to you moving supply because of your debt balance the Debt Assignment Protocol is activated, allowing the switch to continue. It isn’t guaranteed, but it could be an option if you want to switch. Find out more in our &lt;a href=&quot;https://sse.co.uk/help/energy/meters/pay-as-you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PayAsYouGoText {
            get {
                return ResourceManager.GetString("PayAsYouGoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay As You Go meter.
        /// </summary>
        public static string PayGo {
            get {
                return ResourceManager.GetString("PayGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll pay for energy as you go using a payment key or card..
        /// </summary>
        public static string PayGoDisclaimer {
            get {
                return ResourceManager.GetString("PayGoDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment.
        /// </summary>
        public static string PaymentDateLabel {
            get {
                return ResourceManager.GetString("PaymentDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your payment date.
        /// </summary>
        public static string PaymentDetailsEditAlt {
            get {
                return ResourceManager.GetString("PaymentDetailsEditAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details.
        /// </summary>
        public static string PaymentDetailsHeader {
            get {
                return ResourceManager.GetString("PaymentDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PaymentMethodInfoHeader {
            get {
                return ResourceManager.GetString("PaymentMethodInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may change your payment method if you have any outstanding charges on your gas and/or electricity account(s) and/or don’t comply with the terms and conditions relating to that payment method. We’ll write to you about the change at least seven to ten working days before the change begins, in accordance with our Licences. If we change your payment method from Direct Debit to quarterly billing, then you’ll no longer get the Direct Debit discount. This means you’ll pay the equivalent of £40 more per fuel, pe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentMethodParagraphDD {
            get {
                return ResourceManager.GetString("PaymentMethodParagraphDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may change your payment method if you have any outstanding charges on your gas and/or electricity account(s) and/or don’t comply with the terms and conditions relating to that payment method. We’ll write to you about the change at least seven to ten working days before the change begins, in accordance with our Licences..
        /// </summary>
        public static string PaymentMethodParagraphNonDD {
            get {
                return ResourceManager.GetString("PaymentMethodParagraphNonDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        public static string PaymentTypeLabel {
            get {
                return ResourceManager.GetString("PaymentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal details.
        /// </summary>
        public static string PersonalDetailsEditAlt {
            get {
                return ResourceManager.GetString("PersonalDetailsEditAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal details.
        /// </summary>
        public static string PersonalDetailsHeader {
            get {
                return ResourceManager.GetString("PersonalDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to continue and change your personal details.
        /// </summary>
        public static string PersonalDetailsModalButtonAlt {
            get {
                return ResourceManager.GetString("PersonalDetailsModalButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal details.
        /// </summary>
        public static string PersonalDetailsModalButtonText {
            get {
                return ResourceManager.GetString("PersonalDetailsModalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By changing personal details, you’ll be taken back through previous steps and will need to tell us your Direct Debit information again..
        /// </summary>
        public static string PersonalDetailsModalMessage {
            get {
                return ResourceManager.GetString("PersonalDetailsModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to print your order summary.
        /// </summary>
        public static string PrintLinkAlt {
            get {
                return ResourceManager.GetString("PrintLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintLinkText {
            get {
                return ResourceManager.GetString("PrintLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly on Demand.
        /// </summary>
        public static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll pay after you get your quarterly bill..
        /// </summary>
        public static string QuarterlyDisclaimer {
            get {
                return ResourceManager.GetString("QuarterlyDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Extra from the Bundle.
        /// </summary>
        public static string RemoveExtraAlt {
            get {
                return ResourceManager.GetString("RemoveExtraAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this Extra?.
        /// </summary>
        public static string RemoveExtraPromptText {
            get {
                return ResourceManager.GetString("RemoveExtraPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Upgrade from the Bundle.
        /// </summary>
        public static string RemoveUpgradeAlt {
            get {
                return ResourceManager.GetString("RemoveUpgradeAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving you {0} a month.
        /// </summary>
        public static string SavingsPerMonthTxt {
            get {
                return ResourceManager.GetString("SavingsPerMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your order and we’ll switch your energy supply within 21 days.
        /// </summary>
        public static string SidePanel1 {
            get {
                return ResourceManager.GetString("SidePanel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send you a Welcome pack and when your switch is complete, send us your first meter reading.
        /// </summary>
        public static string SidePanel2 {
            get {
                return ResourceManager.GetString("SidePanel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll be in touch when your new Direct Debit plan is set up and your old supplier will send you a final statement.
        /// </summary>
        public static string SidePanel3DD {
            get {
                return ResourceManager.GetString("SidePanel3DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old supplier will send you a final statement or bill.
        /// </summary>
        public static string SidePanelNonDD {
            get {
                return ResourceManager.GetString("SidePanelNonDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  meter (smart).
        /// </summary>
        public static string Smart {
            get {
                return ResourceManager.GetString("Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort code.
        /// </summary>
        public static string SortCodeLabel {
            get {
                return ResourceManager.GetString("SortCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete my order.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to complete your order.
        /// </summary>
        public static string SubmitButtonTitle {
            get {
                return ResourceManager.GetString("SubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the details below and confirm you’ve read the terms and conditions to complete your order..
        /// </summary>
        public static string SummaryIntro {
            get {
                return ResourceManager.GetString("SummaryIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to continue and change your tariff.
        /// </summary>
        public static string TariffDetailsModalButtonAlt {
            get {
                return ResourceManager.GetString("TariffDetailsModalButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new tariffs.
        /// </summary>
        public static string TariffDetailsModalButtonText {
            get {
                return ResourceManager.GetString("TariffDetailsModalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By changing your tariff choice, you’ll be taken back to select a tariff and will need to tell us your Direct Debit information again..
        /// </summary>
        public static string TariffDetailsModalMessage {
            get {
                return ResourceManager.GetString("TariffDetailsModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gas and electricity.
        /// </summary>
        public static string TariffHeaderDual {
            get {
                return ResourceManager.GetString("TariffHeaderDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electricity.
        /// </summary>
        public static string TariffHeaderElectricity {
            get {
                return ResourceManager.GetString("TariffHeaderElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity {0} per month, .
        /// </summary>
        public static string TariffHeaderElectricityMonthlyCost {
            get {
                return ResourceManager.GetString("TariffHeaderElectricityMonthlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gas.
        /// </summary>
        public static string TariffHeaderGas {
            get {
                return ResourceManager.GetString("TariffHeaderGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas {0} per month, .
        /// </summary>
        public static string TariffHeaderGasMonthlyCost {
            get {
                return ResourceManager.GetString("TariffHeaderGasMonthlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} per year. .
        /// </summary>
        public static string TariffHeaderYearlyCost {
            get {
                return ResourceManager.GetString("TariffHeaderYearlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick this box to confirm you agree to these terms and conditions and other product details above..
        /// </summary>
        public static string TermsAndConditionsAriaDescription {
            get {
                return ResourceManager.GetString("TermsAndConditionsAriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Energy - Terms and Conditions - {0}.
        /// </summary>
        public static string TermsAndConditionsPDFAlt {
            get {
                return ResourceManager.GetString("TermsAndConditionsPDFAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy - Terms and Conditions - {0}.
        /// </summary>
        public static string TermsAndConditionsPDFText {
            get {
                return ResourceManager.GetString("TermsAndConditionsPDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas &amp; electricity information.
        /// </summary>
        public static string TillInformationHeaderDual {
            get {
                return ResourceManager.GetString("TillInformationHeaderDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity information.
        /// </summary>
        public static string TillInformationHeaderElectricity {
            get {
                return ResourceManager.GetString("TillInformationHeaderElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas information.
        /// </summary>
        public static string TillInformationHeaderGas {
            get {
                return ResourceManager.GetString("TillInformationHeaderGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Tariff Information Label .
        /// </summary>
        public static string TILLinkAlt {
            get {
                return ResourceManager.GetString("TILLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for Energy - Your order summary - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Phone Package.
        /// </summary>
        public static string UpgradePromptNo {
            get {
                return ResourceManager.GetString("UpgradePromptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this Phone Package.
        /// </summary>
        public static string UpgradePromptNoAlt {
            get {
                return ResourceManager.GetString("UpgradePromptNoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this Phone Package?.
        /// </summary>
        public static string UpgradePromptText {
            get {
                return ResourceManager.GetString("UpgradePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I’m sure.
        /// </summary>
        public static string UpgradePromptYes {
            get {
                return ResourceManager.GetString("UpgradePromptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to remove this Phone Package.
        /// </summary>
        public static string UpgradePromptYesAlt {
            get {
                return ResourceManager.GetString("UpgradePromptYesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This price includes VAT at 5% and any applicable discounts..
        /// </summary>
        public static string VATDisclaimer {
            get {
                return ResourceManager.GetString("VATDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This price includes VAT at 5% and your projected discount ({0} a year for Direct Debit)..
        /// </summary>
        public static string VATDisclaimerDirectDebit {
            get {
                return ResourceManager.GetString("VATDisclaimerDirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link if your meter details are incorrect.
        /// </summary>
        public static string WrongMeterDetailsLinkAlt {
            get {
                return ResourceManager.GetString("WrongMeterDetailsLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong meter details?.
        /// </summary>
        public static string WrongMeterDetailsLinkText {
            get {
                return ResourceManager.GetString("WrongMeterDetailsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your projected monthly bill.
        /// </summary>
        public static string YourProjectedMonthlyBillLbl {
            get {
                return ResourceManager.GetString("YourProjectedMonthlyBillLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bundle.
        /// </summary>
        public static string YourTariffHeaderBundle {
            get {
                return ResourceManager.GetString("YourTariffHeaderBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your energy.
        /// </summary>
        public static string YourTariffHeaderEnergy {
            get {
                return ResourceManager.GetString("YourTariffHeaderEnergy", resourceCulture);
            }
        }
    }
}
