//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Energy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Upgrades_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Upgrades_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Energy.Upgrades_Resources", typeof(Upgrades_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Bundle.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this Upgrade to your Bundle.
        /// </summary>
        public static string AddButtonTextAlt {
            get {
                return ResourceManager.GetString("AddButtonTextAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade your Bundle.
        /// </summary>
        public static string BannerHeader {
            get {
                return ResourceManager.GetString("BannerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Guarantee full details.
        /// </summary>
        public static string FixNFiberPlusImportantInformationPara1_Link1Text {
            get {
                return ResourceManager.GetString("FixNFiberPlusImportantInformationPara1_Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electricalwiringcover.
        /// </summary>
        public static string FixNFibrePlusBannerImageFilename {
            get {
                return ResourceManager.GetString("FixNFibrePlusBannerImageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do lots of people use your home internet at the same time? Then our fastest &lt;strong&gt;Fibre Plus&lt;/strong&gt; broadband might be for you. With unlimited downloads and an average speed of 63Mbps, it&apos;s great for streaming HD movies, playing games online and downloading larger files..
        /// </summary>
        public static string FixNFibrePlusDescPara1 {
            get {
                return ResourceManager.GetString("FixNFibrePlusDescPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line rental is included and we have a range of call packages to suit you, whether you want to make local, national, mobile or international calls..
        /// </summary>
        public static string FixNFibrePlusDescPara2 {
            get {
                return ResourceManager.GetString("FixNFibrePlusDescPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your internet up to {0}Mbps.
        /// </summary>
        public static string FixNFibrePlusHeader {
            get {
                return ResourceManager.GetString("FixNFibrePlusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre Plus broadband – important information.
        /// </summary>
        public static string FixNFibrePlusImportantInformationHeader {
            get {
                return ResourceManager.GetString("FixNFibrePlusImportantInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre Plus broadband – important information.
        /// </summary>
        public static string FixNFibrePlusImportantInformationHeaderAlt {
            get {
                return ResourceManager.GetString("FixNFibrePlusImportantInformationHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave us within 18 months of your start date, we’ll send you a pre-paid envelope to return your router. If you don’t send your router back within 30 working days of getting this envelope, we’ll add a charge of £54 to your account. The broadband speeds quoted above are average speeds at times of peak usage. Broadband speeds and unlimited downloads are subject to our .
        /// </summary>
        public static string FixNFibrePlusImportantInformationPara1_1 {
            get {
                return ResourceManager.GetString("FixNFibrePlusImportantInformationPara1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string FixNFibrePlusImportantInformationPara1_2 {
            get {
                return ResourceManager.GetString("FixNFibrePlusImportantInformationPara1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policies. Actual speeds are dependent upon length and quality of the copper line between your home and your exchange or street cabinet as well as environmental factors within you home such as Wi-Fi interference, in-home wiring and congestion on the service you’re accessing. Customers signing up for SSE fixed-term broadband &amp; phone Bundles can leave their contract without early termination charges if, within the first 60 days, they’re not happy with any aspect of the service they’ve received, and we’ve been  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FixNFibrePlusImportantInformationPara1_3 {
            get {
                return ResourceManager.GetString("FixNFibrePlusImportantInformationPara1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre Plus broadband.
        /// </summary>
        public static string FixNFibrePlusModalProductName {
            get {
                return ResourceManager.GetString("FixNFibrePlusModalProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save £9 a month (£162 over 18 months). £162 saving is based on £9 discount for 18 months for Fibre Plus broadband (18 x £9 = £162), when compared to buying Unlimited Fibre Plus, our equivalent standalone broadband product (£26 per month)..
        /// </summary>
        public static string FixNFibrePlusModalSavingsText {
            get {
                return ResourceManager.GetString("FixNFibrePlusModalSavingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go faster and save.
        /// </summary>
        public static string FixNFibrePlusModalTagline {
            get {
                return ResourceManager.GetString("FixNFibrePlusModalTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £162 saving is based on £9 discount for 18 months for Fibre broadband (18 x £9 = £162), when compared to buying Unlimited Fibre, our equivalent standalone broadband product (£22 per month)..
        /// </summary>
        public static string FixNFibrePlusSavingsCalculatorPara1 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSavingsCalculatorPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £162 saving is based on £9 discount for 18 months for Fibre Plus broadband (18 x £9 = £162), when compared to buying Unlimited Fibre Plus, our equivalent standalone broadband product (£26 per month)..
        /// </summary>
        public static string FixNFibrePlusSavingsPara_PlusPackageAdded {
            get {
                return ResourceManager.GetString("FixNFibrePlusSavingsPara_PlusPackageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Fibre Plus broadband, you’ll get:.
        /// </summary>
        public static string FixNFibrePlusSubHeader1 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our price promise to you: zero price hikes during your 18-month contract.
        /// </summary>
        public static string FixNFibrePlusSubHeader1Bullet1 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited downloads.
        /// </summary>
        public static string FixNFibrePlusSubHeader1Bullet2 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless router.
        /// </summary>
        public static string FixNFibrePlusSubHeader1Bullet3 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line rental included (excludes additional calls and call features).
        /// </summary>
        public static string FixNFibrePlusSubHeader1Bullet4 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1Bullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Happiness Guarantee, so if you’re not completely satisfied with our service, you can leave for free within the first 60 days.
        /// </summary>
        public static string FixNFibrePlusSubHeader1Bullet5 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader1Bullet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your estimated maximum download speed for.
        /// </summary>
        public static string FixNFibrePlusSubHeader2 {
            get {
                return ResourceManager.GetString("FixNFibrePlusSubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to our &lt;b&gt;Fibre Plus&lt;/b&gt; broadband. With unlimited downloads and an average speed of 63Mbps, it&apos;s great for streaming HD movies, playing games online and downloading larger files..
        /// </summary>
        public static string FixNFibrePlusTagline {
            get {
                return ResourceManager.GetString("FixNFibrePlusTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electricalwiringcover.
        /// </summary>
        public static string FixNProtectPlusBannerImageFilename {
            get {
                return ResourceManager.GetString("FixNProtectPlusBannerImageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your heating breaks down, we’ll be there for you – round the clock..
        /// </summary>
        public static string FixNProtectPlusDescPara1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusDescPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get full heating cover 24/7, boiler service included.
        /// </summary>
        public static string FixNProtectPlusHeader {
            get {
                return ResourceManager.GetString("FixNProtectPlusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover – important information.
        /// </summary>
        public static string FixNProtectPlusImportantInformationHeader {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover – important information.
        /// </summary>
        public static string FixNProtectPlusImportantInformationHeaderAlt {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationHeaderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Cover includes 20% VAT and Insurance Premium Tax. Heating Cover has a 12-month fixed-term contract which begins on the next working day after your energy supply switches to us..
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 12 months, you&apos;ll pay the standard price for Heating Cover (currently £23.95). We&apos;ll remind you before the end of your contract that your package price will change..
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara2 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll be contacted to arrange an initial system inspection..
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara3 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and labour are subject to terms and conditions found in the.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara4_1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara4_2 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy is for owners of domestic properties only. Retail, commercial and other premises used for business are not eligible..
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara5 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the SSE Home Services Policy Booklet.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara5_Link1Alt {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara5_Link1Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Home Services Policy Booklet.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara5_Link1Txt {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara5_Link1Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE Home Services Policy Booklet.pdf.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara5_Link1Url {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara5_Link1Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE Heating Cover Insurance Product Information Document.
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara5_Link2Txt {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara5_Link2Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy is for owners of domestic properties only. Retail, commercial and other premises used for business are not eligible..
        /// </summary>
        public static string FixNProtectPlusImportantInformationPara6 {
            get {
                return ResourceManager.GetString("FixNProtectPlusImportantInformationPara6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Cover includes 20% VAT and Insurance Premium Tax. Parts and labour are subject to the terms and conditions found in the .
        /// </summary>
        public static string FixNProtectPlusModalImportantInfoPara1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusModalImportantInfoPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . You’ll be contacted to arrange an initial system inspection. The cost of a boiler service (£90) is based on the price of a standalone SSE Boiler Service.
        /// </summary>
        public static string FixNProtectPlusModalImportantInfoPara2 {
            get {
                return ResourceManager.GetString("FixNProtectPlusModalImportantInfoPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover.
        /// </summary>
        public static string FixNProtectPlusModalProductName {
            get {
                return ResourceManager.GetString("FixNProtectPlusModalProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save £60 over 12 months. £60 saving is based on a £5 discount for 12 months for Heating Cover (12 x £5 = £60), when compared to buying Heating Cover separately (£23.95 per month)..
        /// </summary>
        public static string FixNProtectPlusModalSavingsText {
            get {
                return ResourceManager.GetString("FixNProtectPlusModalSavingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full central heating cover 24/7, boiler service included.
        /// </summary>
        public static string FixNProtectPlusModalTagline {
            get {
                return ResourceManager.GetString("FixNProtectPlusModalTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £114 saving is based on Heating Breakdown being free for 12 months compared to the standard price when bought separately (£9.50 a month): £9.50 x 12 = £114..
        /// </summary>
        public static string FixNProtectPlusSavingsCalculationPara1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSavingsCalculationPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £60 saving is based on a £5 discount for 12 months for Heating Cover (12 x £5 = £60), when compared to buying Heating Cover separately (£23.95 per month)..
        /// </summary>
        public static string FixNProtectPlusSavingsPara_PlusPackageAdded {
            get {
                return ResourceManager.GetString("FixNProtectPlusSavingsPara_PlusPackageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Heating Cover, you’ll get:.
        /// </summary>
        public static string FixNProtectPlusSubHeader1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSubHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour emergency repairs to your boiler and central heating system, parts and labour included.
        /// </summary>
        public static string FixNProtectPlusSubHeader1Bullet1 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSubHeader1Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited call-outs.
        /// </summary>
        public static string FixNProtectPlusSubHeader1Bullet2 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSubHeader1Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual boiler service (worth £90).
        /// </summary>
        public static string FixNProtectPlusSubHeader1Bullet3 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSubHeader1Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-month contract with cover starting on the next working day after your energy supply switches to us.
        /// </summary>
        public static string FixNProtectPlusSubHeader1Bullet4 {
            get {
                return ResourceManager.GetString("FixNProtectPlusSubHeader1Bullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to our &lt;b&gt;Heating Cover&lt;/b&gt; and you’ll not only get 24/7 central heating cover with unlimited call-outs, all parts and labour included. We’ll also give you an annual boiler service..
        /// </summary>
        public static string FixNProtectPlusTagline {
            get {
                return ResourceManager.GetString("FixNProtectPlusTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        public static string PerMonthTxt {
            get {
                return ResourceManager.GetString("PerMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Upgrade from your Bundle.
        /// </summary>
        public static string RemoveButtonAlt {
            get {
                return ResourceManager.GetString("RemoveButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Bundle.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveTxt {
            get {
                return ResourceManager.GetString("SaveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more about how we work out your savings.
        /// </summary>
        public static string SavingsCalculationHeader_Alt {
            get {
                return ResourceManager.GetString("SavingsCalculationHeader_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How your savings are calculated – important information.
        /// </summary>
        public static string SavingsCalculatorHeader {
            get {
                return ResourceManager.GetString("SavingsCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for a Bundle – Choose an Upgrade – SSE.
        /// </summary>
        public static string UpgradesPageTitle {
            get {
                return ResourceManager.GetString("UpgradesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was.
        /// </summary>
        public static string WasTxt {
            get {
                return ResourceManager.GetString("WasTxt", resourceCulture);
            }
        }
    }
}
