//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.TariffChange {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreatePassword_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreatePassword_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.TariffChange.CreatePassword_Resources", typeof(CreatePassword_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be between 7 and 14 characters without any spaces.
        /// </summary>
        public static string Bullet1 {
            get {
                return ResourceManager.GetString("Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must include a combination of upper and lower case letters, with at least one number and/or one of the following special characters @ # ~.
        /// </summary>
        public static string Bullet2 {
            get {
                return ResourceManager.GetString("Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t use anything too obvious like your name or your birthday.
        /// </summary>
        public static string Bullet3 {
            get {
                return ResourceManager.GetString("Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, next.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and continue.
        /// </summary>
        public static string ButtonAlt {
            get {
                return ResourceManager.GetString("ButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without creating an account.
        /// </summary>
        public static string CreateAccountLaterAlt {
            get {
                return ResourceManager.GetString("CreateAccountLaterAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this step.
        /// </summary>
        public static string CreateAccountLaterText {
            get {
                return ResourceManager.GetString("CreateAccountLaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an SSE online account.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just need a password to set up your online account..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a secure password.
        /// </summary>
        public static string ListHeading {
            get {
                return ResourceManager.GetString("ListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords must match. Please check what you’ve entered and try again..
        /// </summary>
        public static string PasswordComparisonError {
            get {
                return ResourceManager.GetString("PasswordComparisonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should be between 7 and 14 characters long. You can use ~ # and @ as well as letters and numbers. It’s also case sensitive so will remember where you use lower or upper case letters..
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should be between 7 and 14 characters long. You can use ~ # and @ as well as letters and numbers. It’s also case sensitive so will remember where you use lower or upper case letters..
        /// </summary>
        public static string PasswordRegExError {
            get {
                return ResourceManager.GetString("PasswordRegExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an online account - Choose your new tariff - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open window with more information.
        /// </summary>
        public static string TooltipAlt {
            get {
                return ResourceManager.GetString("TooltipAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your bills.
        /// </summary>
        public static string TooltipBullet1 {
            get {
                return ResourceManager.GetString("TooltipBullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a meter reading and get an instant balance.
        /// </summary>
        public static string TooltipBullet2 {
            get {
                return ResourceManager.GetString("TooltipBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make payments.
        /// </summary>
        public static string TooltipBullet3 {
            get {
                return ResourceManager.GetString("TooltipBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor your usage with a Smart Meter.
        /// </summary>
        public static string TooltipBullet4 {
            get {
                return ResourceManager.GetString("TooltipBullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opt-in to marketing consent.
        /// </summary>
        public static string TooltipBullet5 {
            get {
                return ResourceManager.GetString("TooltipBullet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image showing an example of an energy usage web page, just some of the information that you can see in your online account..
        /// </summary>
        public static string TooltipImageAlt {
            get {
                return ResourceManager.GetString("TooltipImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s the benefit?.
        /// </summary>
        public static string TooltipLabelText {
            get {
                return ResourceManager.GetString("TooltipLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See below for message.
        /// </summary>
        public static string TooltipScreenReader {
            get {
                return ResourceManager.GetString("TooltipScreenReader", resourceCulture);
            }
        }
    }
}
