//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.TariffChange {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fallout_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fallout_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.TariffChange.Fallout_Resources", typeof(Fallout_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re unable to change your tariff online.
        /// </summary>
        public static string AccountInelegibleHeader {
            get {
                return ResourceManager.GetString("AccountInelegibleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change tariff online.
        /// </summary>
        public static string AccountInelegibleTitle {
            get {
                return ResourceManager.GetString("AccountInelegibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, but we can’t show your available tariffs at the moment.
        /// </summary>
        public static string CTCUnavailableHeader {
            get {
                return ResourceManager.GetString("CTCUnavailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll have our system back up and running as soon as possible..
        /// </summary>
        public static string CTCUnavailableText1 {
            get {
                return ResourceManager.GetString("CTCUnavailableText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please come back and try again later..
        /// </summary>
        public static string CTCUnavailableText2 {
            get {
                return ResourceManager.GetString("CTCUnavailableText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariffs unavailable.
        /// </summary>
        public static string CTCUnavailableTitle {
            get {
                return ResourceManager.GetString("CTCUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  if you’re deaf or have hearing loss..
        /// </summary>
        public static string GettingInTouchSuffix {
            get {
                return ResourceManager.GetString("GettingInTouchSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your fixed rate tariff has expired in the last 30 days you can still choose a new fixed rate tariff online. You’ll just need your account number and postcode..
        /// </summary>
        public static string LapsedFixedRateTariffText1 {
            get {
                return ResourceManager.GetString("LapsedFixedRateTariffText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find your account number on your latest bill. If you have a Gas and Electricity account with us, you’ll only need to enter details for one of them to change your tariff for both..
        /// </summary>
        public static string LapsedFixedRateTariffText2 {
            get {
                return ResourceManager.GetString("LapsedFixedRateTariffText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all other tariff changes give us a call on .
        /// </summary>
        public static string LapsedFixedRateTariffText3 {
            get {
                return ResourceManager.GetString("LapsedFixedRateTariffText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re currently on a Standard tariff.
        /// </summary>
        public static string LapsedFixedRateTariffTitle {
            get {
                return ResourceManager.GetString("LapsedFixedRateTariffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string LinkBackToHome {
            get {
                return ResourceManager.GetString("LinkBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string LinkBackToHomeAlt {
            get {
                return ResourceManager.GetString("LinkBackToHomeAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your new tariff.
        /// </summary>
        public static string LinkChooseTariff {
            get {
                return ResourceManager.GetString("LinkChooseTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your new tariff.
        /// </summary>
        public static string LinkChooseTariffAlt {
            get {
                return ResourceManager.GetString("LinkChooseTariffAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://renew.sse.co.uk/compare?project=tariffchange.
        /// </summary>
        public static string LinkChooseTariffURL {
            get {
                return ResourceManager.GetString("LinkChooseTariffURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting in touch.
        /// </summary>
        public static string LinkGettingInTouch {
            get {
                return ResourceManager.GetString("LinkGettingInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting in touch if you’re deaf or have hearing loss.
        /// </summary>
        public static string LinkGettingInTouchAlt {
            get {
                return ResourceManager.GetString("LinkGettingInTouchAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sse.co.uk/help/accessibility/getting-in-touch-deaf-or-hearing-loss.
        /// </summary>
        public static string LinkGettingInTouchURL {
            get {
                return ResourceManager.GetString("LinkGettingInTouchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call 0330 102 8313.
        /// </summary>
        public static string LinkPhoneAlt {
            get {
                return ResourceManager.GetString("LinkPhoneAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0330 102 8313.
        /// </summary>
        public static string LinkPhoneText {
            get {
                return ResourceManager.GetString("LinkPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:03301028313.
        /// </summary>
        public static string LinkPhoneURL {
            get {
                return ResourceManager.GetString("LinkPhoneURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your SSE online account.
        /// </summary>
        public static string MySSEUrlLinkText {
            get {
                return ResourceManager.GetString("MySSEUrlLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE online account.
        /// </summary>
        public static string MySSEUrlTitleText {
            get {
                return ResourceManager.GetString("MySSEUrlTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can’t match your account number and postcode.
        /// </summary>
        public static string NotMatchedHeader {
            get {
                return ResourceManager.GetString("NotMatchedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t match postcode.
        /// </summary>
        public static string NotMatchedTitle {
            get {
                return ResourceManager.GetString("NotMatchedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t find page.
        /// </summary>
        public static string PageNotFoundHeader {
            get {
                return ResourceManager.GetString("PageNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but we can’t find the page you’re looking for..
        /// </summary>
        public static string PageNotFoundParagraph {
            get {
                return ResourceManager.GetString("PageNotFoundParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t find page.
        /// </summary>
        public static string PageNotFoundTitle {
            get {
                return ResourceManager.GetString("PageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, due to the payment plan you currently have we’re unable to change your tariff online.
        /// </summary>
        public static string PaymentInelegibleHeader {
            get {
                return ResourceManager.GetString("PaymentInelegibleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change tariff online.
        /// </summary>
        public static string PaymentInelegibleTitle {
            get {
                return ResourceManager.GetString("PaymentInelegibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a call on .
        /// </summary>
        public static string PhonePrefix {
            get {
                return ResourceManager.GetString("PhonePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and we’ll help you choose your new tariff..
        /// </summary>
        public static string PhoneSuffix {
            get {
                return ResourceManager.GetString("PhoneSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current tariff is due to end in the next two months.
        /// </summary>
        public static string RenewalHeader {
            get {
                return ResourceManager.GetString("RenewalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can still choose a new tariff online, all you need is your account number. You’ll find it on the recent letter we sent you or on your bills. If you have a gas and electric account, you only need to use one..
        /// </summary>
        public static string RenewalParagraph {
            get {
                return ResourceManager.GetString("RenewalParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new tariff.
        /// </summary>
        public static string RenewalTitle {
            get {
                return ResourceManager.GetString("RenewalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something’s gone wrong.
        /// </summary>
        public static string TechFaultHeader {
            get {
                return ResourceManager.GetString("TechFaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t worry, we’ll get things back up and running as soon as possible..
        /// </summary>
        public static string TechFaultParagraph {
            get {
                return ResourceManager.GetString("TechFaultParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again shortly..
        /// </summary>
        public static string TechFaultParagraph2 {
            get {
                return ResourceManager.GetString("TechFaultParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical fault.
        /// </summary>
        public static string TechFaultTitle {
            get {
                return ResourceManager.GetString("TechFaultTitle", resourceCulture);
            }
        }
    }
}
