//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.TariffChange {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TariffSummary_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TariffSummary_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.TariffChange.TariffSummary_Resources", typeof(TariffSummary_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand.
        /// </summary>
        public static string AccordionAlt {
            get {
                return ResourceManager.GetString("AccordionAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important information.
        /// </summary>
        public static string AccordionHeader {
            get {
                return ResourceManager.GetString("AccordionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On selecting your new tariff if we feel that, based on your known historical consumption and any debit balances, there’s a reasonable risk that the Direct Debit amounts would not be enough to cover your usage, we retain the right to conduct a review of your Direct Debit payment amounts. If this is the case, you’ll receive a letter confirming these new amounts..
        /// </summary>
        public static string AccordionParagraph1 {
            get {
                return ResourceManager.GetString("AccordionParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may change your payment method if you have any outstanding charges on your gas and/or electricity account(s) and/or do not comply with the terms and conditions relating to that payment method. We’ll write to you letting you know of the change at least seven working days before it begins to apply, in accordance with our Licences. If we change your payment method from Direct Debit to quarterly billing then you’ll no longer benefit from the Direct Debit discount..
        /// </summary>
        public static string AccordionParagraph2 {
            get {
                return ResourceManager.GetString("AccordionParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select a new tariff on this website, you’ll stay with your current SSE brand..
        /// </summary>
        public static string AccordionParagraph3 {
            get {
                return ResourceManager.GetString("AccordionParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the Terms &amp; Conditions for the {0} tariff below. Please read our full Terms &amp; Conditions below..
        /// </summary>
        public static string AccordionParagraph4 {
            get {
                return ResourceManager.GetString("AccordionParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE and associated brands: Southern Electric, Scottish Hydro, SWALEC and Atlantic are all trading names of OVO Electricity Limited registered in England and Wales number 06858121 (supply of electricity) and OVO (S) Gas Limited registered in England and Wales number 02716495 (supply of gas). The registered office of OVO Electricity Limited and OVO (S) Gas Limited is 1 Rivergate, Temple Quay, Bristol, BS1 6ED..
        /// </summary>
        public static string AccordionParagraph5 {
            get {
                return ResourceManager.GetString("AccordionParagraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit amounts.
        /// </summary>
        public static string AccordionSection1 {
            get {
                return ResourceManager.GetString("AccordionSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string AccordionSection2 {
            get {
                return ResourceManager.GetString("AccordionSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staying with SSE Southern Electric, SSE SWALEC or SSE Scottish Hydro?.
        /// </summary>
        public static string AccordionSection3 {
            get {
                return ResourceManager.GetString("AccordionSection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string AccordionSection4 {
            get {
                return ResourceManager.GetString("AccordionSection4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are.
        /// </summary>
        public static string AccordionSection5 {
            get {
                return ResourceManager.GetString("AccordionSection5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Payment Details.
        /// </summary>
        public static string AdditionalInfoHeader {
            get {
                return ResourceManager.GetString("AdditionalInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount(s) below are rounded up to the nearest pound and will be taken from your bank account on the date shown..
        /// </summary>
        public static string AdditionalInfoIntroMonthly {
            get {
                return ResourceManager.GetString("AdditionalInfoIntroMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Direct Debit amount(s) below are rounded up to the nearest pound and will be taken from your bank account on the date shown..
        /// </summary>
        public static string AdditionalInfoIntroMonthlyDD {
            get {
                return ResourceManager.GetString("AdditionalInfoIntroMonthlyDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bill will show the amount(s) to be taken from your bank account and the date this will take effect..
        /// </summary>
        public static string AdditionalInfoIntroVariable {
            get {
                return ResourceManager.GetString("AdditionalInfoIntroVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bill will show the Direct Debit amount(s) to be taken from your bank account and the date this will take effect..
        /// </summary>
        public static string AdditionalInfoIntroVariableDD {
            get {
                return ResourceManager.GetString("AdditionalInfoIntroVariableDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tariff choice.
        /// </summary>
        public static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tariff choice.
        /// </summary>
        public static string BackLinkAlt {
            get {
                return ResourceManager.GetString("BackLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incl. VAT at 5% &amp; any applicable discounts.
        /// </summary>
        public static string Breakdown1 {
            get {
                return ResourceManager.GetString("Breakdown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected monthly cost breakdown:.
        /// </summary>
        public static string Breakdown2 {
            get {
                return ResourceManager.GetString("Breakdown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected annual cost breakdown:.
        /// </summary>
        public static string Breakdown3 {
            get {
                return ResourceManager.GetString("Breakdown3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tariff.
        /// </summary>
        public static string ChangeTariffAlt {
            get {
                return ResourceManager.GetString("ChangeTariffAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I have read and agreed to the terms and conditions.
        /// </summary>
        public static string CheckboxLabel {
            get {
                return ResourceManager.GetString("CheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you confirm your order, please read our terms and conditions:.
        /// </summary>
        public static string ConfirmationHeader {
            get {
                return ResourceManager.GetString("ConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may get your switching details and Welcome Pack via email..
        /// </summary>
        public static string ConfirmationIntro {
            get {
                return ResourceManager.GetString("ConfirmationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a fixed price tariff and pay by Direct Debit or standing order, for most fixed tariffs you’ll get a discount of £40 a year for each fuel when compared to other ways of paying. The discount is applied to your standing charge on a pence per day basis, until your tariff ends..
        /// </summary>
        public static string DDPara1 {
            get {
                return ResourceManager.GetString("DDPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a standard variable tariff, your energy prices are capped and the maximum price you pay (known as a cap) is set by Ofgem, the energy regulator. If you pay by Direct Debit or standing order, your standing charge and unit prices will be discounted. Your discount will vary depending on how much energy you use, where you live and your meter type. If you qualified for Warm Home Discount before 1 August 2019, your prices will be discounted regardless of how you pay..
        /// </summary>
        public static string DDPara2 {
            get {
                return ResourceManager.GetString("DDPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain tariffs do not qualify for Direct Debit and standing order discounts. Please check the tariff terms and conditions for details..
        /// </summary>
        public static string DDPara3 {
            get {
                return ResourceManager.GetString("DDPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new tariff will start on .
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity per month.
        /// </summary>
        public static string ElectricityPerMonth {
            get {
                return ResourceManager.GetString("ElectricityPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE is a trading name of OVO Electricity Limited registered in England and Wales number 06858121 (supply of electricity), OVO (S) Gas Limited registered in England and Wales number 02716495 (supply of gas) and OVO (S) Home Services Limited (boiler and heating repair, servicing, cover, boiler Installations and electrical wiring cover). The registered office of OVO Electricity Limited and OVO (S)OVO (S) Gas Limited is 1 Rivergate, Temple Quay, Bristol, BS1 6ED.
        ///
        ///The registered office of OVO (S) Home Service [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FixAndProtectAccordionParagraph5 {
            get {
                return ResourceManager.GetString("FixAndProtectAccordionParagraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;By ticking this box, you confirm:&lt;/p&gt;
        ///&lt;div&gt;
        ///&lt;ol&gt;
        ///&lt;li&gt;You’re happy to enter into a binding contract with OVO Electricity Limited/OVO (S) Gas Limited for your gas/electricity supply and OVO (S) Home Services Limited for any Home Services products (and, for any insurance products, also AmTrust Europe Limited) for the SSE products I have selected.&lt;/li&gt;
        ///&lt;li&gt;I have read and accept the 1 Year Fix and Protect v3 Terms and Conditions (which also includes a summary of the tariff) and the General Terms and Cond [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FixAndProtectCheckboxLabelHeader {
            get {
                return ResourceManager.GetString("FixAndProtectCheckboxLabelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may get your switching details and Welcome Pack via email for Energy. You will also receive a confirmation of sale letter for your SSE Heating Breakdown Cover separately confirming your product start date. This will include your policy booklet with terms and conditions..
        /// </summary>
        public static string FixAndProtectConfirmationIntro {
            get {
                return ResourceManager.GetString("FixAndProtectConfirmationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For SSE Home Services products, your Cancellation Period will be 14 calendar days from the day you receive your confirmation of contract. If you expressly request for SSE to carry out any work during your Cancellation Period, you may need to pay for the work SSE has undertaken..
        /// </summary>
        public static string FixAndProtectSummaryPargraph1 {
            get {
                return ResourceManager.GetString("FixAndProtectSummaryPargraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas per month.
        /// </summary>
        public static string GasPerMonth {
            get {
                return ResourceManager.GetString("GasPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read our full Terms &amp; Conditions below:.
        /// </summary>
        public static string GeneralPDFLabel {
            get {
                return ResourceManager.GetString("GeneralPDFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re almost done.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for more information.
        /// </summary>
        public static string InformationLinkAlt {
            get {
                return ResourceManager.GetString("InformationLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the details and confirm you’ve read the terms and conditions to complete your tariff selection..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you understand the information above..
        /// </summary>
        public static string IsTermsAndConditionsCheckedLabelAlt {
            get {
                return ResourceManager.GetString("IsTermsAndConditionsCheckedLabelAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I have read and agreed to the terms and conditions.
        /// </summary>
        public static string IsTermsAndConditionsCheckedLabelText {
            get {
                return ResourceManager.GetString("IsTermsAndConditionsCheckedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the statements above and select the tick box to confirm you agree..
        /// </summary>
        public static string IsTermsAndConditionsCheckedValidationError {
            get {
                return ResourceManager.GetString("IsTermsAndConditionsCheckedValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment each month.
        /// </summary>
        public static string MonthlyCollectionDayText {
            get {
                return ResourceManager.GetString("MonthlyCollectionDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE  is now part of  the OVO family, which means some of your communications may say SSE Home Services and some may mention OVO (S) Home Services. This will not negatively impact the product or service that you will receive.  Please bear with us as we update all of our communications accordingly..
        /// </summary>
        public static string OVODisclaimerText {
            get {
                return ResourceManager.GetString("OVODisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Confirm order&quot; you are confirming you are the account holder and have authorisation from (any or all) other account holders to make changes to the account(s)..
        /// </summary>
        public static string PostLoginAuthorisationText {
            get {
                return ResourceManager.GetString("PostLoginAuthorisationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected monthly cost:.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new tariff will start on.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your right to change your mind.
        /// </summary>
        public static string SummaryHeading1 {
            get {
                return ResourceManager.GetString("SummaryHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Calculation.
        /// </summary>
        public static string SummaryHeading2 {
            get {
                return ResourceManager.GetString("SummaryHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may send your confirmation of contract by email after you’ve confirmed your new tariff selection. You can cancel your agreement without charge within 14 days from the day after the date you signed up to this tariff. We’ll include details of how to cancel when we send this to you. Alternatively, you can get in touch using our contact us page..
        /// </summary>
        public static string SummaryParagraph1 {
            get {
                return ResourceManager.GetString("SummaryParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’re paying by Direct Debit, we’ve calculated the monthly amount by dividing your personal projection by 12 and rounding it up to the nearest pound..
        /// </summary>
        public static string SummaryParagraph2 {
            get {
                return ResourceManager.GetString("SummaryParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Terms and Conditions.
        /// </summary>
        public static string TermsAndConditionsLabel {
            get {
                return ResourceManager.GetString("TermsAndConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your order - Choose your new tariff - SSE.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string VariableFrequencyText {
            get {
                return ResourceManager.GetString("VariableFrequencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices are inclusive of VAT at 5%..
        /// </summary>
        public static string VATRateParagraph {
            get {
                return ResourceManager.GetString("VATRateParagraph", resourceCulture);
            }
        }
    }
}
