//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankDetailsCommon_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankDetailsCommon_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Common.BankDetailsCommon_Resources", typeof(BankDetailsCommon_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the holder of the bank account we will take Direct Debit payments from..
        /// </summary>
        public static string AccountHolderAriaDescription {
            get {
                return ResourceManager.GetString("AccountHolderAriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the account number for the bank account we will take Direct Debit payments from..
        /// </summary>
        public static string AccountNumberAriaDescription {
            get {
                return ResourceManager.GetString("AccountNumberAriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tick box confirms you are the account holder and only person needed to set up Direct Debit for this bank account..
        /// </summary>
        public static string AuthorisedAriaDescription {
            get {
                return ResourceManager.GetString("AuthorisedAriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select this box to confirm this statement is correct or contact us to complete your order..
        /// </summary>
        public static string AuthorisedRequiredError {
            get {
                return ResourceManager.GetString("AuthorisedRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am the account holder and the only person needed to set up a Direct Debit for this account. If either of these are not the case, please contact us on 0345 026 7058..
        /// </summary>
        public static string AuthorisedText {
            get {
                return ResourceManager.GetString("AuthorisedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband &amp; Phone: .
        /// </summary>
        public static string BroadbandLabel {
            get {
                return ResourceManager.GetString("BroadbandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0345 026 7058.
        /// </summary>
        public static string CallUsPhone {
            get {
                return ResourceManager.GetString("CallUsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call 0345 026 7058.
        /// </summary>
        public static string CallUsPhoneAlt {
            get {
                return ResourceManager.GetString("CallUsPhoneAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel:0345 026 7058.
        /// </summary>
        public static string CallUsPhoneUrl {
            get {
                return ResourceManager.GetString("CallUsPhoneUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/DD Guarantee SSE.pdf.
        /// </summary>
        public static string DD_Guarantee_PDFLink {
            get {
                return ResourceManager.GetString("DD_Guarantee_PDFLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/Phone and Broadband - General Terms and Conditions for the Supply of Fix and Fibre Broadband and Phone Package.pdf.
        /// </summary>
        public static string DD_Guarantee_PDFLink_Broadband {
            get {
                return ResourceManager.GetString("DD_Guarantee_PDFLink_Broadband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE_Home_Services_Limited_DD_Guarantee _V1.00.pdf.
        /// </summary>
        public static string DD_Guarantee_PDFLink_HomeServices {
            get {
                return ResourceManager.GetString("DD_Guarantee_PDFLink_HomeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the date that we will take your energy Direct Debit payment each month..
        /// </summary>
        public static string DDPaymentDateAlt {
            get {
                return ResourceManager.GetString("DDPaymentDateAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity: .
        /// </summary>
        public static string ElectricityLabel {
            get {
                return ResourceManager.GetString("ElectricityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to energy – Your Direct Debit details - SSE.
        /// </summary>
        public static string EnergyPageTitle {
            get {
                return ResourceManager.GetString("EnergyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Direct Debit payment date (1st-28th).
        /// </summary>
        public static string EnergySubHeader2 {
            get {
                return ResourceManager.GetString("EnergySubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to order summary page.
        /// </summary>
        public static string EnergySubmitButtonAlt {
            get {
                return ResourceManager.GetString("EnergySubmitButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas: .
        /// </summary>
        public static string GasLabel {
            get {
                return ResourceManager.GetString("GasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit details.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Heating Breakdown and Electrical Wiring Cover Direct Debit Guarantee.
        /// </summary>
        public static string HesElecWiringPDFLinkAlt {
            get {
                return ResourceManager.GetString("HesElecWiringPDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown Cover and Electrical Wiring Cover - Direct Debit Guarantee - Download PDF.
        /// </summary>
        public static string HesElecWiringPDFLinkText {
            get {
                return ResourceManager.GetString("HesElecWiringPDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Heating Breakdown Cover Direct Debit Guarantee.
        /// </summary>
        public static string HesPDFLinkAlt {
            get {
                return ResourceManager.GetString("HesPDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown Cover - Direct Debit Guarantee - Download PDF.
        /// </summary>
        public static string HesPDFLinkText {
            get {
                return ResourceManager.GetString("HesPDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Heating Cover and Electrical Wiring Cover Direct Debit Guarantee.
        /// </summary>
        public static string HesPlusElecWiringPDFLinkAlt {
            get {
                return ResourceManager.GetString("HesPlusElecWiringPDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover and Electrical Wiring Cover - Direct Debit Guarantee - Download PDF.
        /// </summary>
        public static string HesPlusElecWiringPDFLinkText {
            get {
                return ResourceManager.GetString("HesPlusElecWiringPDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Heating Cover Direct Debit Guarantee.
        /// </summary>
        public static string HesPlusPDFLinkAlt {
            get {
                return ResourceManager.GetString("HesPlusPDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover - Direct Debit Guarantee - Download PDF.
        /// </summary>
        public static string HesPlusPDFLinkText {
            get {
                return ResourceManager.GetString("HesPlusPDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown: £0.
        /// </summary>
        public static string HesWhyDoIPay0ModalHeader {
            get {
                return ResourceManager.GetString("HesWhyDoIPay0ModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll set up this Direct Debit now. Your Heating Breakdown is free for 12 months and then charged at the standard price thereafter (currently £9.50 a month)..
        /// </summary>
        public static string HesWhyDoIPay0ModalText {
            get {
                return ResourceManager.GetString("HesWhyDoIPay0ModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am the account holder and the only person needed to set up a Direct Debit for this account. If either of these are not the case, please contact us on &lt;strong&gt;0345 026 7058.&lt;/strong&gt;.
        /// </summary>
        public static string HomeServicesAuthorisedText {
            get {
                return ResourceManager.GetString("HomeServicesAuthorisedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown: .
        /// </summary>
        public static string HomeServicesLabel {
            get {
                return ResourceManager.GetString("HomeServicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover: .
        /// </summary>
        public static string HomeServicesPlusLabel {
            get {
                return ResourceManager.GetString("HomeServicesPlusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Direct Debit payment:.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The safeguards and guarantees that you have with Direct Debit also apply when you set up a Direct Debit online. You can read about these in the Direct Debit guarantee below. You can download and read, save, or print our Direct Debit Guarantee by clicking on the link below..
        /// </summary>
        public static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of each month..
        /// </summary>
        public static string PaymentDatePostfix {
            get {
                return ResourceManager.GetString("PaymentDatePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take payment on.
        /// </summary>
        public static string PaymentDatePrefix {
            get {
                return ResourceManager.GetString("PaymentDatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download our Direct Debit Guarantee.
        /// </summary>
        public static string PDFLinkAlt {
            get {
                return ResourceManager.GetString("PDFLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Guarantee - Download PDF.
        /// </summary>
        public static string PDFLinkText {
            get {
                return ResourceManager.GetString("PDFLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If either of these are not the case, please contact us on .
        /// </summary>
        public static string PhonePrefix {
            get {
                return ResourceManager.GetString("PhonePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sse.co.uk is secure.
        /// </summary>
        public static string SecureLogoText {
            get {
                return ResourceManager.GetString("SecureLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the sort code for the bank account we will take Direct Debit payments from..
        /// </summary>
        public static string SortCodeAriaDescription {
            get {
                return ResourceManager.GetString("SortCodeAriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit agreement.
        /// </summary>
        public static string SubHeader {
            get {
                return ResourceManager.GetString("SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit payment date (1st-28th).
        /// </summary>
        public static string SubHeader2 {
            get {
                return ResourceManager.GetString("SubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Direct Debit payments:.
        /// </summary>
        public static string SubHeader3 {
            get {
                return ResourceManager.GetString("SubHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Direct Debit Guarantee.
        /// </summary>
        public static string SubHeader4 {
            get {
                return ResourceManager.GetString("SubHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do I pay for Broadband &amp; Phone?.
        /// </summary>
        public static string WhenDoIPayLinkAlt {
            get {
                return ResourceManager.GetString("WhenDoIPayLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do I pay for Broadband &amp; Phone?.
        /// </summary>
        public static string WhenDoIPayLinkText {
            get {
                return ResourceManager.GetString("WhenDoIPayLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll send you a monthly bill for your broadband and phone and collect your Direct Debit payment about two weeks later. We’ll let you know your payment date on your bill..
        /// </summary>
        public static string WhenDoIPayPopupText {
            get {
                return ResourceManager.GetString("WhenDoIPayPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband &amp; Phone Direct Debit.
        /// </summary>
        public static string WhenDoIPayPopupTextHeader {
            get {
                return ResourceManager.GetString("WhenDoIPayPopupTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is there a £0 payment?.
        /// </summary>
        public static string WhyIsThere0PaymentLinkAlt {
            get {
                return ResourceManager.GetString("WhyIsThere0PaymentLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is there a £0 payment?.
        /// </summary>
        public static string WhyIsThere0PaymentLinkText {
            get {
                return ResourceManager.GetString("WhyIsThere0PaymentLinkText", resourceCulture);
            }
        }
    }
}
