//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductFeatures_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductFeatures_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Common.ProductFeatures_Resources", typeof(ProductFeatures_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New installation fee: £60.
        /// </summary>
        public static string ApplyInstallationFeeText {
            get {
                return ResourceManager.GetString("ApplyInstallationFeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40% OFF.
        /// </summary>
        public static string BroadbandBundlePackagePriceLbl {
            get {
                return ResourceManager.GetString("BroadbandBundlePackagePriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line rental included.
        /// </summary>
        public static string BroadbandFeature1 {
            get {
                return ResourceManager.GetString("BroadbandFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18-month contract.
        /// </summary>
        public static string BroadbandFeature2 {
            get {
                return ResourceManager.GetString("BroadbandFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free phone line installation (usually £60).
        /// </summary>
        public static string BroadbandFeature3 {
            get {
                return ResourceManager.GetString("BroadbandFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband: .
        /// </summary>
        public static string BroadbandLabel {
            get {
                return ResourceManager.GetString("BroadbandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre Plus broadband.
        /// </summary>
        public static string BroadbandPlusProductDisplayText {
            get {
                return ResourceManager.GetString("BroadbandPlusProductDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre broadband.
        /// </summary>
        public static string BroadbandProductDisplayText {
            get {
                return ResourceManager.GetString("BroadbandProductDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre broadband.
        /// </summary>
        public static string BroadbandSubLabel {
            get {
                return ResourceManager.GetString("BroadbandSubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-months contract.
        /// </summary>
        public static string ContractLengthFeature {
            get {
                return ResourceManager.GetString("ContractLengthFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Wiring Cover.
        /// </summary>
        public static string ElectricalWiringDisplayText {
            get {
                return ResourceManager.GetString("ElectricalWiringDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string ElectricityLabel {
            get {
                return ResourceManager.GetString("ElectricityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour emergency repairs to your boiler and central heating system, parts and labour included.
        /// </summary>
        public static string FixNProtectBullet1 {
            get {
                return ResourceManager.GetString("FixNProtectBullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-month contract with cover starting on the next working day after your energy supply switches to us..
        /// </summary>
        public static string FixNProtectBullet2 {
            get {
                return ResourceManager.GetString("FixNProtectBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £90 excess per call-out.
        /// </summary>
        public static string FixNProtectBullet3 {
            get {
                return ResourceManager.GetString("FixNProtectBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Heating Breakdown, you&apos;ll get:.
        /// </summary>
        public static string FixNProtectBulletListHeader {
            get {
                return ResourceManager.GetString("FixNProtectBulletListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s an excess?.
        /// </summary>
        public static string FixNProtectExcessHeader {
            get {
                return ResourceManager.GetString("FixNProtectExcessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excess is the amount you&apos;ll need to pay for each claim you make. So you&apos;d pay {0} each time you make a claim..
        /// </summary>
        public static string FixNProtectExcessText {
            get {
                return ResourceManager.GetString("FixNProtectExcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 emergency repairs, including parts and labour.
        /// </summary>
        public static string FixNProtectFeature1 {
            get {
                return ResourceManager.GetString("FixNProtectFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £90 excess per call-out.
        /// </summary>
        public static string FixNProtectFeature2 {
            get {
                return ResourceManager.GetString("FixNProtectFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-month contract.
        /// </summary>
        public static string FixNProtectFeature3 {
            get {
                return ResourceManager.GetString("FixNProtectFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for Heating Breakdown includes Insurance Premium Tax. Parts and labour are subject to the terms and conditions found in the .
        /// </summary>
        public static string FixNProtectImportantPara1 {
            get {
                return ResourceManager.GetString("FixNProtectImportantPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual boiler service included.
        /// </summary>
        public static string FixNProtectPlusFeature2 {
            get {
                return ResourceManager.GetString("FixNProtectPlusFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to £0 excess per call-out.
        /// </summary>
        public static string FixNProtectPlusFeature4 {
            get {
                return ResourceManager.GetString("FixNProtectPlusFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown.
        /// </summary>
        public static string FixNProtectProductDisplayText {
            get {
                return ResourceManager.GetString("FixNProtectProductDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re here for you if your heating breaks down - round the clock..
        /// </summary>
        public static string FnPDescription {
            get {
                return ResourceManager.GetString("FnPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string FnPPrice {
            get {
                return ResourceManager.GetString("FnPPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 cover for your central heating system.
        /// </summary>
        public static string FnPTagline {
            get {
                return ResourceManager.GetString("FnPTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be added to a future bill..
        /// </summary>
        public static string FutureBillInstallationText {
            get {
                return ResourceManager.GetString("FutureBillInstallationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string GasLabel {
            get {
                return ResourceManager.GetString("GasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string HesBundlePackagePriceLbl {
            get {
                return ResourceManager.GetString("HesBundlePackagePriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Breakdown.
        /// </summary>
        public static string HesPackageDisplayText {
            get {
                return ResourceManager.GetString("HesPackageDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Cover.
        /// </summary>
        public static string HesPackagePlusDisplayText {
            get {
                return ResourceManager.GetString("HesPackagePlusDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-off cost:.
        /// </summary>
        public static string Oneoffcost {
            get {
                return ResourceManager.GetString("Oneoffcost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone line installation fee.
        /// </summary>
        public static string PhonelineInstallationFeeText {
            get {
                return ResourceManager.GetString("PhonelineInstallationFeeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full product details.
        /// </summary>
        public static string ViewFullDetailsAltText {
            get {
                return ResourceManager.GetString("ViewFullDetailsAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full details.
        /// </summary>
        public static string ViewFullDetailsLink {
            get {
                return ResourceManager.GetString("ViewFullDetailsLink", resourceCulture);
            }
        }
    }
}
