//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out of your account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous page.
        /// </summary>
        public static string BackButtonAlt {
            get {
                return ResourceManager.GetString("BackButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step in your Bundle sign-up.
        /// </summary>
        public static string BundleButtonNextSignUpAlt {
            get {
                return ResourceManager.GetString("BundleButtonNextSignUpAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to next step in the sign-up.
        /// </summary>
        public static string ButtonNextSignUpAlt {
            get {
                return ResourceManager.GetString("ButtonNextSignUpAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to next step in the energy sign-up.
        /// </summary>
        public static string ButtonNextSignUpEnergyAlt {
            get {
                return ResourceManager.GetString("ButtonNextSignUpEnergyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, next.
        /// </summary>
        public static string ButtonNextText {
            get {
                return ResourceManager.GetString("ButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept &amp; Close.
        /// </summary>
        public static string CookieClose {
            get {
                return ResourceManager.GetString("CookieClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes this message.
        /// </summary>
        public static string CookieCloseAlt {
            get {
                return ResourceManager.GetString("CookieCloseAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to provide a better website experience. By using our site, you’re agreeing to our use of cookies. For more information,.
        /// </summary>
        public static string CookiesDisclaimerText {
            get {
                return ResourceManager.GetString("CookiesDisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read our cookies policy..
        /// </summary>
        public static string CookiesLink {
            get {
                return ResourceManager.GetString("CookiesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our cookies policy (opens in a new tab).
        /// </summary>
        public static string CookiesLinkAlt {
            get {
                return ResourceManager.GetString("CookiesLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sse.co.uk/about-us/legal/cookie-policy.
        /// </summary>
        public static string CookiesLinkURL {
            get {
                return ResourceManager.GetString("CookiesLinkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the day your current tariff ends.
        /// </summary>
        public static string CurrentTariffText {
            get {
                return ResourceManager.GetString("CurrentTariffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string ExtrasHeader {
            get {
                return ResourceManager.GetString("ExtrasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/yourSSE.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our Facebook page.
        /// </summary>
        public static string FacebookLinkAlt {
            get {
                return ResourceManager.GetString("FacebookLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full terms and conditions.
        /// </summary>
        public static string FullTermsAndConditionsHeader {
            get {
                return ResourceManager.GetString("FullTermsAndConditionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further information about our tariffs, please read our terms and conditions below..
        /// </summary>
        public static string FullTermsAndConditionsPara {
            get {
                return ResourceManager.GetString("FullTermsAndConditionsPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}/home.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our homepage.
        /// </summary>
        public static string HomepageAlt {
            get {
                return ResourceManager.GetString("HomepageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sse.co.uk/home.
        /// </summary>
        public static string HomePageUrl {
            get {
                return ResourceManager.GetString("HomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string LineRentalTalkPriceText {
            get {
                return ResourceManager.GetString("LineRentalTalkPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string LinkBackToHome {
            get {
                return ResourceManager.GetString("LinkBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string LinkBackToHomeAlt {
            get {
                return ResourceManager.GetString("LinkBackToHomeAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Your account.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout - Your account.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to open dialogue box.
        /// </summary>
        public static string ModalAlt {
            get {
                return ResourceManager.GetString("ModalAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close dialogue box.
        /// </summary>
        public static string ModalCloseButtonAlt {
            get {
                return ResourceManager.GetString("ModalCloseButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ModalCloseButtonText {
            get {
                return ResourceManager.GetString("ModalCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t find page.
        /// </summary>
        public static string PageNotFoundHeader {
            get {
                return ResourceManager.GetString("PageNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but we can’t find the page you’re looking for..
        /// </summary>
        public static string PageNotFoundParagraph {
            get {
                return ResourceManager.GetString("PageNotFoundParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t find page.
        /// </summary>
        public static string PageNotFoundTitle {
            get {
                return ResourceManager.GetString("PageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone package.
        /// </summary>
        public static string PhonePackageHeader {
            get {
                return ResourceManager.GetString("PhonePackageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our privacy policy.
        /// </summary>
        public static string PrivacyPolicyAlt {
            get {
                return ResourceManager.GetString("PrivacyPolicyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sse.co.uk/about-us/legal/privacy-policy.
        /// </summary>
        public static string PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("PrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string RadioNoAlt {
            get {
                return ResourceManager.GetString("RadioNoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string RadioYesAlt {
            get {
                return ResourceManager.GetString("RadioYesAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesNo.
        /// </summary>
        public static string RadioYesNoName {
            get {
                return ResourceManager.GetString("RadioYesNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the radio buttons below to select which date you’d like your tariff to start.
        /// </summary>
        public static string RenewalHelpText {
            get {
                return ResourceManager.GetString("RenewalHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like your new tariff to start?.
        /// </summary>
        public static string RenewalModalTitle {
            get {
                return ResourceManager.GetString("RenewalModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE.
        /// </summary>
        public static string SSE {
            get {
                return ResourceManager.GetString("SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Pdfs/SSE GEN T&amp;CS JANUARY 2020.pdf.
        /// </summary>
        public static string SSE_GeneralTermsAndConditionsForTheSupplyOfElectricityAndOrGas {
            get {
                return ResourceManager.GetString("SSE_GeneralTermsAndConditionsForTheSupplyOfElectricityAndOrGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE (OVO Electricity Limited).
        /// </summary>
        public static string SSEElectricitySupplier {
            get {
                return ResourceManager.GetString("SSEElectricitySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE (OVO (S) Gas Limited).
        /// </summary>
        public static string SSEGasSupplier {
            get {
                return ResourceManager.GetString("SSEGasSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something’s gone wrong.
        /// </summary>
        public static string TechFaultHeader {
            get {
                return ResourceManager.GetString("TechFaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t worry, we’ll get things back up and running as soon as possible..
        /// </summary>
        public static string TechFaultParagraph {
            get {
                return ResourceManager.GetString("TechFaultParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again shortly..
        /// </summary>
        public static string TechFaultParagraph2 {
            get {
                return ResourceManager.GetString("TechFaultParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical fault.
        /// </summary>
        public static string TechFaultTitle {
            get {
                return ResourceManager.GetString("TechFaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our legal terms of use.
        /// </summary>
        public static string TermsOfUseAlt {
            get {
                return ResourceManager.GetString("TermsOfUseAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sse.co.uk/about-us/legal/terms-of-use.
        /// </summary>
        public static string TermsOfUseLink {
            get {
                return ResourceManager.GetString("TermsOfUseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodaysDate {
            get {
                return ResourceManager.GetString("TodaysDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/YourSSE.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our Twitter page.
        /// </summary>
        public static string TwitterLinkAlt {
            get {
                return ResourceManager.GetString("TwitterLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are.
        /// </summary>
        public static string WhoWeAre {
            get {
                return ResourceManager.GetString("WhoWeAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our corporate descriptor.
        /// </summary>
        public static string WhoWeAreAlt {
            get {
                return ResourceManager.GetString("WhoWeAreAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sse.co.uk/about-us/legal/trading-as-statement.
        /// </summary>
        public static string WhoWeAreLink {
            get {
                return ResourceManager.GetString("WhoWeAreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/yourSSEtv.
        /// </summary>
        public static string YouTubeLink {
            get {
                return ResourceManager.GetString("YouTubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to our YouTube channel.
        /// </summary>
        public static string YouTubeLinkAlt {
            get {
                return ResourceManager.GetString("YouTubeLinkAlt", resourceCulture);
            }
        }
    }
}
