//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.WebModel.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tariff_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tariff_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Products.WebModel.Resources.Common.Tariff_Resources", typeof(Tariff_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Smart Home Package with a Google Nest Thermostat E (RRP £199) and a Google Nest Mini (RRP £49) – total saving £248&lt;/p&gt;&lt;p&gt;Includes a smart meter installation at no extra cost&lt;/p&gt;.
        /// </summary>
        public static string FixAndControlTariffCardText {
            get {
                return ResourceManager.GetString("FixAndControlTariffCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Drive for free with SSE  –  free electricity for up to 8,000 miles when you charge your electric vehicle during off-peak hours&lt;/p&gt;
        ///&lt;p&gt;Fixed energy prices  –  guaranteed no price rises for 12 months&lt;/p&gt;
        ///&lt;p&gt;100% renewable electricity  –  we’ll match your usage with power from wind and water&lt;/p&gt;
        ///&lt;p&gt;Includes upgrade to a compatible (SMETS2) smart meter, if you don’t have one&lt;/p&gt;.
        /// </summary>
        public static string FixAndDriveTariffCardText {
            get {
                return ResourceManager.GetString("FixAndDriveTariffCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;18 Month Fix and Fibre Bundle includes phone line rental and 35Mbps average download speed (subject to fibre availability)&lt;/p&gt;
        ///&lt;p&gt; Redeem your £13.00 SSE fibre broadband after confirming your order&lt;/p&gt;
        ///&lt;p&gt; Early exit fee 38 pence per remaining day of your 18-month broadband contract &lt;/p&gt;.
        /// </summary>
        public static string FixAndFibreTariffCardText {
            get {
                return ResourceManager.GetString("FixAndFibreTariffCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Includes 1 year free SSE Heating Breakdown Cover worth £114 (£9.50 per month) – £90 excess per call out and other terms and conditions apply&lt;/p&gt;.
        /// </summary>
        public static string FixAndProtectTariffCardText {
            get {
                return ResourceManager.GetString("FixAndProtectTariffCardText", resourceCulture);
            }
        }
    }
}
